### ISSUE TITLE
Scope issue with s-exprs when using 0.10.0 binary

### ISSUE THREAD

**Issue by crisptrutski** [alda-lang/alda#115]
Running `boot alda -x "play -f test/examples/bach_cello_suite_no_1.alda"` from the source for `0.10.0` works great.

Running `alda play -f test/examples/bach_cello_suite_no_1.alda"`, with the same version installed, is not working however...

`clojure.lang.ExceptionInfo: Unable to resolve symbol: tempo! in this context`

This sounds like it's related to the recent parser simplifications, but strange that it only affects the build. From the sounds of #114 this issue may not even be occurring for other users.

**Comment by daveyarwood** [comment]
Will investigate today. 

I've gotten the cyclic load dependency intermittently when requiring certain namespaces in Vim. I think it will help if we get rid of all the `in-ns` sorcery and use explicit namespaces for everything, with `alda.lisp` explicitly importing the stuff that should be available. That should give us greater control of what namespaces require what other namespaces. I think the problem is that, with inline Clojure expressions, `alda.parser` has to(?) require `alda.lisp` in order to resolve vars from that namespace, but `alda.lisp/alda-code` needs to require `alda.parser` in order to parse code at eval-time.

I actually got "Unable to resolve symbol: tempo" yesterday in the middle of my lightning talk about Alda at ClojureBridge, although I was demonstrating the parsing steps by parsing/eval'ing/playing manually in a REPL session with `alda.lisp` required in, and I left out the `:refer :all`. I wonder if there is some namespace in the Alda codebase that just has `(require '[alda.lisp])` without the `:refer :all`?

**Comment by daveyarwood** [comment]
Oh! Of course this causes problems -- I modified the `alda` script to refer `alda.lisp` into the `boot.user` namespace so that the changes work. Users will need to update their `/usr/local/bin/alda` with the new version.

I just reproduced the problem, then ran `cp bin/alda /usr/local/bin` and the problem is solved.

**Comment by crisptrutski** [comment]
Perhaps alda should have some way to update this script itself? eg. `alda update`

**Comment by daveyarwood** [comment]
I like that idea. Just not sure how to make it Windows-friendly... although right now, to my knowledge no one running Windows is able to use the script anyway :P

**Comment by daveyarwood** [comment]
Here's one possible way we could handle this -- the user would run:

    alda script > /usr/local/bin/alda

`alda script` just grabs the latest `alda` script from GitHub and prints it to STDOUT, which can then be redirected to a file. I prefer this approach to making assumptions about where the user might want the script :)
