### ISSUE TITLE
weird behaviours with new note lengths

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#141]
These might be intended, but I noticed a couple of issues with the note lengths when I was playing around with the REPL:

* when I ran the command `piano: c0.5s`, the REPL threw a syntax error. I'm guessing this is a parsing error, as the parser was probably expecting an integer (same happens for `piano: c0.5ms`, but fractions of a millisecond aren't really needed). 
* when I ran the command `piano: c1000000s`, I expected the note to play "indefinitely" (12 days), however I noticed it sounded exactly the same as `piano: c5s`, that is, if the length was longer than around five seconds, it pretty much played for the exact same time, tapering off in the same way.

**Comment by daveyarwood** [comment]
Thanks for reporting. I think both behaviors are by design. 

Second/millisecond lengths must be in integers, which should be OK since milliseconds can be used if you need fractions of a second, and you shouldn't ever need fractions of a millisecond :)

It seems like some MIDI instruments have a natural decay, whereas others will sustain indefinitely. I'm sure this varies from soundfont to soundfont. The piano is an instrument that doesn't sustain infinitely in real life, which I think the soundfont creators were trying to imitate. There are other instruments that will sustain indefinitely -- try some strings and winds, for instance (violin, cello, bassoon, flute, etc.)
