### ISSUE TITLE
Re-add a long comment syntax?

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#142]
I noticed, when looking through the changeling, that alda no longer has a long comment syntax, with the former being `(* *)`. Why not use Java's comment syntax of `/* */`, or why not extend the short syntax of `#` to `#* *#`?

**Comment by daveyarwood** [comment]
We had to do away with the `(* ... *)` syntax when inline Clojure expressions were added, which made it so that anything between parentheses would be interpreted as a Clojure expression.

While I'm not opposed to adding another long comment syntax, I personally don't think long comments are a necessary thing for a language to have -- it's something I've been thinking about more now that Alda's syntax is evolving and becoming more complex. In practice, a lot of text editors make it easy for you comment and uncomment many lines of code (using "short comments" commenting out an entire line). It's also possible to use Clojure's `comment` macro to comment out a block of Alda code, like this:

```
piano:
  c d (comment e f g) a b > c
```

Obviously, that's a little more cumbersome than having a dedicated long comment syntax, but my thought right now is that I'm hesitant to add more complexity into our grammar (which is already growing quite complex) if we don't need to. That being said, I'm not opposed to adding a new long comment syntax if it's what the people want™. Leaving this issue open for discussion.

**Comment by daveyarwood** [comment]
I'm still not really in favor of adding a long comment syntax, but I'll leave this open for discussion until we get closer to Alda 1.0.0, at which point we'll need to decide for sure what we want to do. I'd love to get some more input on this -- do people feel like long comments are a must-have for Alda?

**Comment by MadcapJake** [comment]
I agree with your points on adding complexity and especially that editors provide commenting functionality that is often easier to work with than long-form comments.  Using them inline is also going to obfuscate your code so having to use the rather long `(comment ...)` form is a good hindrance to anyone wanting to use them! :grin:

**Comment by daveyarwood** [comment]
Closing this issue for now, though I will certainly keep the window open for further discussion about long comment syntax in the future.
