### ISSUE TITLE
Export to Csound score?

### ISSUE THREAD

**Issue by PaulBatchelor** [alda-lang/alda#148]
Hi there. 

My motivation behind this feature request is that you could use other musical languages more geared for audio DSP to be your synthesis engine. Csound and my own projects (Sporth, Soundpipe, Polypipe) come to mind. Happy to help where I can, although I have no experience in Clojure. 

A Csound score is nothing more than a text-based table with whitespace separated values. They are generally quite trivial to produce. If your language could support this, I could immediately incorporate Alda into my existing workflow, which would be cool for me :)

A generated score could look like this:

i 1 0 1 60 0.5
i 1 1 1 62 0.5
i 3 0 3 64 0.1
- Every score line starts with an 'i' indicating an instrument event, and the parameters (called p values) follow, white-space separated
- p value 1 is the instrument number to play 
- p value 2 is the time in seconds to start (a time of zero means start immediately)
- p value 3 is the duration (in seconds) of the note
- p value 4 is the MIDI note number
- p value 5 is the amplitude

p-values 1,2,3 are mandatory. 4 and 5 are just what I typically use (you can tack on an arbitrary number of p values too). 

It would be ideal to be able to write this to standard output or to a FIFO, as Csound can read these events in realtime. 

Let me know what is possible, impossible. Thanks!

**Comment by daveyarwood** [comment]
This is exactly the kind of thing I've been hoping to make easier with Alda. I looked into Csound a bit, and it's a powerful platform for sure, but its syntax is a bit cumbersome, which is a turn-off for me as a composer. I feel like representing notes in "musical terms" makes more sense for people who want to create music.

I'm definitely in favor of being able to export scores from Alda -> Csound. This is totally doable. :+1: 

With the variety of formats we will eventually want to support for exporting Alda scores (MIDI, WAV, LilyPond, etc.), I think we are headed towards an `alda export` task. It could parse and evaluate the Alda score the same way as we already do -- which generates a general-purpose [map of score data](https://github.com/alda-lang/alda/blob/master/doc/alda-lisp.md#parsing-demo) -- but instead of using the `alda.sound/play!` function to play the score, we would use the score data to spit out files, write to STDOUT, feed things to Csound in real time, etc. We have things set up pretty modularly, so we should be able to just write new code without modifying much (if anything) of our existing code.

I'm fairly busy these days, and could use more hands on deck in general with Alda, but I might try and play around with this sometime, if I have a minute.

If anyone else feels like trying their hand at this, please feel free! :)

**Comment by daveyarwood** [comment]
@PaulBatchelor If you feel like taking a stab at a PR for this, I'll be happy to review your code and help you with any Clojure-related questions/issues you may run into.

**Comment by PaulBatchelor** [comment]
@daveyarwood For people not familiar with DSP and modular synthesis, a language like Csound can be quite daunting. It would neat to create a library of pre-built instruments and effects specifically to be played by Alda generated scores. You wouldn't have to touch a line of Csound, let alone *see* a line of Csound code. I'd be happy to build these instruments. 

I am a bit limited on time myself, but you can assign this task to me and I'll try to add this feature as a way of learning Alda.

**Comment by daveyarwood** [comment]
@PaulBatchelor That would be awesome! Thanks!

Alda doesn't support modular synthesis "natively" yet (just general MIDI at this point), so this would a killer feature because it would basically give Alda score-writers some new instruments to play with.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-core/issues/10.
