### ISSUE TITLE
Error message line numbers / better parse error reporting

### ISSUE THREAD

**Issue by MadcapJake** [alda-lang/alda#150]
Line numbers given in a parse error don't match the file.  They seem to be related to lines of notes only but I am not positive on this.

**Comment by daveyarwood** [comment]
This is a consequence of the recent changes I made to the parser. I made it so that parsing happens in several stages (some of which can be parallelized for better performance). An unfortunate consequence is that since we're not parsing the whole file in one pass, we lose the ability to have accurate line numbers, and the error reporting is a bit more vague because it sometimes deals with intermediate data.

I'd happily accept a PR if anyone is interested in tackling this. I think one way to fix it would be a separate "error finding" step that runs only in the case of a parse error, and uses a single grammar in order to give you a proper line number and more accurate error message. The grammar could be a dumbed-down version of the grammar we had before, maybe. We might not even need a grammar for this at all, just a series of regular expressions to catch common errors and report them.

**Comment by elyisgreat** [comment]
Was going to report this very issue. Currently only the generic `ERROR [alda.repl.core] - Invalid Alda syntax.` error is reported, except for some errors which throw a clojure/java exception (see `c0` and `(tempo 0)`). Better error descriptions would also be nice, such as 
```
ERROR [alda.repl.core] - line 1 - 'c d +e f g a b' - invalid Alda syntax.
                                                           ^
```

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-core/issues/12.
