### ISSUE TITLE
Allow fractional / decimal note lengths

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#193]
I was playing around with the repl when I found an interesting bug. When I tried to play a `c0`, instead of getting this error, like I got for entering `c0.5`

```
ERROR [alda.repl.core] - Invalid Alda syntax.
```

which indicates that the compiler caught the error

I got this error

```
                                               alda.Client.main      Client.java:  324
                                      alda.AldaServer.startRepl  AldaServer.java:  400
                                        alda.Util.callClojureFn        Util.java:  362
                                                            ...                       
                                          alda.repl/start-repl!         repl.clj:   37
                                          alda.repl/start-repl!         repl.clj:   49
                                       alda.repl/start-repl!/fn         repl.clj:   58
                                    alda.repl/start-repl!/fn/fn         repl.clj:   73
                                      alda.repl.core/interpret!         core.clj:   50
                                              clojure.core/eval         core.clj: 3105
                                                            ...                       
                                   clojure.core$eval9231.invoke   NO_SOURCE_FILE      
                             clojure.core$eval9231.invokeStatic   NO_SOURCE_FILE      
                                             clojure.core/doall         core.clj: 3039
                                             clojure.core/dorun         core.clj: 3024
                                               clojure.core/seq         core.clj:  137
                                                            ...                       
         clojure.core$eval9231$iter__9232__9236$fn__9237.invoke   NO_SOURCE_FILE      
clojure.core$eval9231$iter__9232__9236$fn__9237$fn__9243.invoke   NO_SOURCE_FILE      
                                          alda.lisp/note-length     duration.clj:   28
                                          alda.lisp/note-length     duration.clj:   30
java.lang.AssertionError: Assert failed: (pos? number)
```

Also, ~~there's no reason why c0.5 shouldn't work~~ notation issue. In fact, any rational number could be used, however `/` wouldn't be a good notation. Perhaps `l` (or `L`)? For example `3l16` would be the equivalent length of 3 16th notes.

**Comment by daveyarwood** [comment]
I think throwing an exception is fine here, though I welcome other viewpoints. My 2¢: technically `c0` is "valid syntax," as it's a note followed by a duration, but the score evaluation environment needs the number to be positive because a note length of "0" makes no sense, so there is an assertion that the number be positive (hence the assertion error).

I agree that there's no reason not to allow rational numbers as note lengths, even if it would be kind of a narrow use case. `c0.5` would theoretically be twice as long as a whole note `c1`, and `c1.5` would be halfway between the length of a half note `c2` and a whole note `c1` (so I guess the same length as a dotted half note `c2.`)

**Comment by elyisgreat** [comment]
I think it makes more sense for 0 to be a syntax error rather than a runtime error, as the duration implies a length of 1/duration measures (or 4/duration internally). 1/0 is an illegal argument to begin with, so I don't see why a runtime error is any better than a syntax error. I sort of assume that any error handling that would throw a clojure/Java exception would be handled by Alda internally and only expect error messages from Alda. There might be reasoning for throwing clojure/Java errors that I might not be aware of. 

For rational rhythms, I prefer a numerator and denominator syntax as opposed to a decimal syntax, as it's more flexible and doesn't conflict with the already existing `.` syntax (so long as `/` was not used). Of course, if you wanted to implement decimals as well you could use an alternate decimal syntax, such as `,` .

**Comment by daveyarwood** [comment]
I think the way we handle syntax vs. runtime exceptions is perhaps better handled in a separate issue. I think it would be ideal if Alda could provide specific error messages instead of barfing out a stacktrace, but that will take some thought, especially with parse errors (see #150).

I'm not sure I'm completely following the numerator/denominator syntax you're proposing.

> For example 3l16 would be the equivalent length of 3 16th notes.

You could represent this in Alda as `c16~16~16` or `c8.`. I appreciate the idea for having a dedicated syntax for representing "3 x 16th note," but I'm not sure if it would be practical enough to be worth making the syntax more complex -- I think I'd rather keep it simple.

On the other hand, I think it would be nice to allow score writers the flexibility to represent note lengths that are slightly off from whole-number note lengths. You can already do things that aren't possible with standard notation, such as `c5` -- a "fifth" note, which is somewhere in between a quarter note and a triplet quarter note. I like the idea of going even farther and allowing things like `c4.5`, which is halfway between a quarter note and a "fifth" note. A practical use of this would be decimal numbers between 0 and 1, which could be a convenient way to represent [note values longer than a whole note](https://en.wikipedia.org/wiki/Note_value) -- double whole note/breve would be `c0.5`, longa would be `c0.25`, maxima would be `c0.125`.

**Comment by elyisgreat** [comment]
By using the decimal notation alone you run into problems with things like 3 1-notes; 0.333333... with rational notation this isn't a problem. I suppose you could use `duration`, however it's weird in that `(duration 1)` represents a 1/4 note...

**Comment by daveyarwood** [comment]
I think we could leave it up to the composer to deal with things like this responsibly\*, since I think it would be pretty rare to need to use a note duration with a repeating decimal. I see what you're getting at, though... it is generally better to work with rational numbers because they're more precise in cases like that. I'm still hesitant to add more literal syntax to the language, if we can avoid it.

\*The composer should understand that in experimenting with these non-standard note lengths, he/she may end up with slight mistimings that are inherent in working with floating-point numbers. He/she could get around that by using more exact numbers (0.33333333 vs. just 0.33), using markers to line things back up when desired, or by using `set-duration` with a rational number.

The gotcha with `set-duration` (and by extension, `duration`) is that that value is a number of beats, not a note value. So, the equivalent of setting the note value to "0.33333" would be `(set-duration 12)`. (The note value `0.33333` is 3 times longer than a whole note, which has a note value of `1` and is 4 beats long; 4 beats x 3 = 12 beats.  The formula for this is `4 / note value = number of beats`.)

We should probably have a `set-note-value` so that the composer doesn't have to do this calculation him/herself.

**Comment by elyisgreat** [comment]
with 1.0.0-rc15 the `duration` attribute doesn't work anymore and is replaced with `set-duration`. Is this for consistency when this gets added?

**Comment by daveyarwood** [comment]
It's more of an implementation detail.

Before 1.0.0-rc15, `duration` was both a way to specify a note duration, and it had the side effect of setting the current default duration of all current instruments.

Now, with the way the code has been rewritten, `duration` is only a way to specify a note duration. For example, in a Clojure REPL:

```
boot.user=> (duration (note-length 4))
{:beats 1.0, :ms 0, :slurred false, :duration? true}
```

`duration` no longer has side effects, it just takes any number of note lengths and returns a map containing some context information including the total number of beats.

The side effect of setting the current instruments' default duration still happens, but now it's part of Alda's internal logic, which is cleaner from a programming perspective. The ability to set duration is still available, though, as the function `set-duration`.

**Comment by elyisgreat** [comment]
I thought it's an attribute... I'm confused

**Comment by daveyarwood** [comment]
Sorry, I could do a better job of explaining this.

In the [alda.lisp DSL](https://github.com/alda-lang/alda/blob/master/doc/alda-lisp.md), the equivalent of a C quarter note (i.e. `c4` in Alda syntax) is `(note (pitch :c) (duration (note-length 4)))`.

Before:

* `set-duration` was an attribute setter
* `duration` was the way to represent the duration of a note in alda.lisp, but it also implicitly called `set-duration` when it was called (this is what programmers call a "side effect", and it's often not considered a good practice to have side effects)

Now:

* `set-duration` is still an attribute setter
* `duration` is still the way to represent a note duration in alda.lisp, and it no longer has side effects

So now, because `duration` no longer has side effects, `set-duration` must be used directly if you want to set the duration attribute.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-core/issues/16.
