### ISSUE TITLE
Attributes do not check for valid input data

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#195]
I was playing around with attributes recently, and I found something interesting in the way attributes handle input data. I noticed that almost all attributes do not check for invalid input data, only for an invalid data type (they also always throw java/clojure exceptions as well; never alda ones). This leads to some interesting cases:

1. Duplicate/Invalid key signatures  
Key signatures that are invalid have no effect. `piano: (key-sig "x+") o4 d e f g a b > c d` runs exactly the same as `piano: o4 d e f g a b > c d`. Key signatures that are duplicates choose the latter note. `piano: (key-sig "f+ f- g+ g-") o4 d e f g a b > c d` runs exactly the same as `piano: (key-sig "f- g-") o4 d e f g a b > c d`
2. Invalid durations  
Durations should be positive. Nonpositive durations have no effect. `piano: (duration 0) o4 d e f g a b > c d` runs exactly like `piano: o4 d e f g a b > c d`
3. Invalid Octaves  
Octaves should be integers. `piano: (octave 4.5) d e f g a b > c d` runs the code as if it was running `piano: (octave 4) d++++++ e++++++ f++++++ g++++++ a++++++ b++++++ > c++++++ d++++++`. This *kind of* makes sense due to how octaves work philosophically, but it's inconsistent with the syntax (`piano: (octave 4.5) d e f g a b o5.5 c d` throws an Alda syntax error)
4. Invalid Tempos  
Tempos should be positive real numbers. running `piano: (tempo 0) o4 d e f g a b > c d` throws a divide by zero error, however negative tempos do not throw errors. I haven't figured out what negative tempos do; they behave very weirdly.
5. Invalid Quantization  
Quantization should be between 0 and 100. Negative quantizations throw an error, however `piano: (quant 1000) d e f g a b o5 c d` runs exactly like `piano: (quant 100) d e f g a b o5 c d` and doesn't throw an error. 

Panning, volume, and track-volume check for valid input data properly.

**Comment by daveyarwood** [comment]
Attributes will generally throw exceptions at eval-time rather than at parse-time, because they are implemented as Clojure expressions. The parser will interpret anything between parentheses as a Clojure expression, so it will parse OK as long as what's inside is valid Clojure code. [The parser is very liberal about what can be considered Clojure code](https://github.com/alda-lang/alda/blob/master/server/grammar/clojure.bnf), as it's easier (and more performant) to just say "anything between parentheses is Clojure code," and let the Clojure process sort out what is and isn't valid at run-time.

The nice thing about sorting out these things at run-time is that it's easy to validate values by using preconditions. [Here's an example](https://github.com/alda-lang/alda/blob/master/server/src/alda/lisp/attributes.clj#L30-L39) where the `octave` attribute uses a precondition to validate that the value is either a number or `:up` or `:down`.

I agree with you on most of your points above about validating values for certain attributes. We should improve this by adding validations.

My only comment is re: quantization, we actually allow quantizing above 100% because it allows you to easily write a part with overlapping notes, which can be a nice effect for piano, guitar, etc. The notes still end up being timed the same, they'll just overlap if quantization is > 100.

TODO:

- [ ] Key signature: validate no duplicate letters, and that there are no letters outside the A-G range. (Currently we ignore these issues, but it would be better to throw an error so the user is aware if they're doing something invalid.)
- [ ] Duration: validate that the number is positive.
- [ ] Octave: validate that the number is an integer.
- [ ] Tempo: validate that the number is positive.

**Comment by daveyarwood** [comment]
@jgkamat Would you be interested in taking a stab at this? It's low-hanging fruit, would be a good first issue to tackle in the Clojure part of Alda :)

If not, I can knock it out sometime soon.

**Comment by elyisgreat** [comment]
Yeah. The quantization above 100 would be really cool to have as a feature. From what I observed, it made no difference as of now. 

Negative tempos could also be used to make the score play backwards.

**Comment by daveyarwood** [comment]
> Negative tempos could also be used to make the score play backwards.


![](https://media.giphy.com/media/k7nUblXRPCsc8/giphy.gif)

**Comment by elyisgreat** [comment]
Sarcasm?

Anyway, I realize that the logic of it might be confusing (ex. `(tempo 120) c d e f g (tempo -120)` creating an infinite loop), but I'm sure it can be worked out.

**Comment by jgkamat** [comment]
@daveyarwood I can definitely take a shot at this sometime today or tomorrow (but this would be my first ever clojure code so the quality would be questionable at best). Should I do something similar to [the way octave did it](https://github.com/alda-lang/alda/blob/master/server/src/alda/lisp/attributes.clj#L30-L39)?

**Comment by daveyarwood** [comment]
@elyisgreat Jokes aside, that's a really interesting idea. I think it would be difficult to implement, though.

@jgkamat No problem at all -- feel free to bug me with Clojure questions, I'm happy to help! If you'd like, you can submit a "rough draft" PR, and I can review that code and we can go from there.

We should use preconditions -- `octave` is a good example. We do have some ["predefined" transformations](https://github.com/alda-lang/alda/blob/master/server/src/alda/lisp/attributes.clj#L9-L15) that we're using. I could see us adding some new ones like `positive-percentage`, which would be just like `percentage` but with an additional precondition that the number has to be positive.

**Comment by elyisgreat** [comment]
Oh. Also, `(println ($attribute))` does not work with abbreviated attribute names. I'm not sure if this is intended or not, as attributes are more linguistic features (even though they're technically clojure code), while `(println ($attribute))` is more like inline clojure code.

**Comment by daveyarwood** [comment]
@elyisgreat What do you mean by "does not work"? Are you getting an error, or is it just not printing? One consequence of our recent move to server/client infrastructure is that you can't see stuff printing unless you have the server running in the foreground, which is not the default behavior when you start a server.

**Comment by daveyarwood** [comment]
You should be able to see things printing in the foreground in the REPL, though.

**Comment by elyisgreat** [comment]
`(println ($quant))` throws this error:
```
           alda.Client.main      Client.java:  324
  alda.AldaServer.startRepl  AldaServer.java:  400
    alda.Util.callClojureFn        Util.java:  362
                        ...                       
      alda.repl/start-repl!         repl.clj:   37
      alda.repl/start-repl!         repl.clj:   49
   alda.repl/start-repl!/fn         repl.clj:   58
alda.repl/start-repl!/fn/fn         repl.clj:   73
  alda.repl.core/interpret!         core.clj:   50
          clojure.core/eval         core.clj: 3105
                        ...                       
             java.lang.RuntimeException: Unable to resolve symbol: $quant in this context
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: $quant in this context, compiling:(NO_SOURCE_PATH:0:0)
```

while `(println ($quantization))` prints out the actual quantization (though it prints it out of 1 instead of 100).

**Comment by elyisgreat** [comment]
this is in the REPL btw

**Comment by daveyarwood** [comment]
Ah, I see -- yeah, that's something we could change. I would accept a PR if someone wants to make that change. The `$`-prefixed getter function thing isn't something I would consider part of the "public API" for Alda, though.

**Comment by daveyarwood** [comment]
Fixed in [1.0.0-rc12](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc12).

**Comment by elyisgreat** [comment]
checked and they all seem to be good. I noticed though that `midi-synth-voice: (quant 0) c d e f g` is audible. Is this intended?

**Comment by daveyarwood** [comment]
@elyisgreat Nope -- that's a bug. Notes should be silent if quantization is 0%. I'll create a new issue to address that. Thanks for the heads up!
