### ISSUE TITLE
Syntax does not completely ignore bar lines

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#196]
Bar lines (`|`) should be completely ignored by the syntax (except when used within inline clojure code), however sometimes they get in the way and throw syntax errors.

`c4~|4|d|e|f|g` - runs normally
`c2|d|e|f|g` - runs normally
`c|2|d|e|f|g` - throws syntax error

There's also a weird syntax error that I found when using bars like so:

```
midi-synth-voice:

V1: g4 r2. | >e4 d8 c4 d4. | <b4. r a-4 | >e4 d c< b8 | > c8~2..< g|
V2: [o3 r4. (quant 50) g4. g8 r8|]*2 [o3 r4. (quant 50) g4. g8 r8|]*2
```

I haven't figured out what causes it yet.

**Comment by daveyarwood** [comment]
Thanks for reporting all these issues -- it will help us fix a number of bugs.

The thing about barlines is that we say we "ignore" them as if they were whitespace, but they are actually considered significant events, as we will eventually use them to do things like generate sheet music.

Perhaps we should adjust our documentation so that we're more clear about where it's OK to use barlines. It would be more accurate to say that barlines may be placed in between events. Your example above `c|2|d|e|f|g` is not valid Alda syntax because `2` is not an event. The parser sees `c`, then a barline, then `2`, and it doesn't know what to do with `2` so it throws a syntax error.

It looks like we probably have a bug related to barlines that's causing your example to fail to parse... I'll dig in later when I have a minute.

**Comment by elyisgreat** [comment]
Couldn't you generate sheet music by providing a time signature and have it generate the bars automatically?

**Comment by daveyarwood** [comment]
Yes, but I'd like to make it possible to set your barlines wherever you'd like, too, for greater flexibility.

**Comment by elyisgreat** [comment]
perhaps it could be implemented as an attribute or syntax feature; that way you could change it mid-score. I was using the baronies merely to group my notes together; Sometimes it's easier to write without them.

**Comment by daveyarwood** [comment]
I'm thinking we could add a `time-sig` attribute, analogous to `key-sig`. The composer will be free to use a time signature or not use a time signature, whichever he/she prefers. We can make Alda smart enough to figure out where the barlines should go based on the combination of the time signature (if there is one) and the explicit barlines placed by the composer.

**Comment by elyisgreat** [comment]
Probably the best option. In any case, there should be stricter and more through documentation on how bar lines work and where to use them.

**Comment by daveyarwood** [comment]
Definitely.

But, there is also a parsing bug here, probably related to the bug I described in this other issue [here](https://github.com/alda-lang/alda/issues/197#issuecomment-193832088).

The parser gets tripped up here (where the arrow is pointing):
```
V1: g4 r2. | >e4 d8 c4 d4. | <b4. r a-4 | >e4 d c< b8 | > c8~2..< g| # <-
V2: [o3 r4. (quant 50) g4. g8 r8|]*2 [o3 r4. (quant 50) g4. g8 r8|]*2
```

If you remove the whitespace (including the newline) between the barline and `V2`, it parses.

We need to adjust the grammar so that it will allow whitespace between a barline/Clojure expression at the end of one voice and the start of the next voice.

**Comment by daveyarwood** [comment]
Fixed in [1.0.0-rc11](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc11).

**Comment by elyisgreat** [comment]
barlines are not considered valid event separators. `piano: c|d|e` throws a syntax error. This should probably be fixed, or perhaps they are to be treated as individual events?

**Comment by daveyarwood** [comment]
Hmm, I think you're right. We can treat them kind of like we treat the
octave operators, where it's OK to include them before and after events
without space in between.

**Comment by elyisgreat** [comment]
Yep. Although keep in mind #97 for when you're trying to fix this

**Comment by daveyarwood** [comment]
On further thought, this is not something we can support, for the same reasons that we do not allow whitespace between other events, the only exception being that it's OK for notes/chords/rests to be preceded/followed by the octave up/down operators.

Aside from that one exception, it is not valid to leave out spaces between events. Barlines are considered events; they do not currently do anything, but in the future they will represent a sort of "end this measure" operator when dealing with sheet music.

Invalid: 

```
c|d|e|f|g
```

Valid:

```
c | d | e | f | g
```

While the latter is more key presses, it is preferable for two reasons:

- It's less confusing to parse. (We would have to significantly alter the grammar to allow for the edge case of leaving out spaces between notes when there is a barline, resulting in a grammar that's harder to understand and work with, and it would also slow down the parser to some degree. Having a more complicated grammar would also make it easier for unexpected bugs to crop up.)

- It looks better -- Valid Alda scores will be easier to read.

**Comment by daveyarwood** [comment]
One minor note: we do support the exception where it's OK to tie note durations across a barline. For example, this is valid:

```
c1|~1|~1|~1
```

The parser reads this as a single note consisting of four tied whole notes; the barlines are actually included as part of the note event.

**Comment by elyisgreat** [comment]
Interesting. This explains why a barline can succeed a note but not precede one...

**Comment by daveyarwood** [comment]
Hmm... interestingly, `c1| d` is valid, but `c1 |d` is not. This is because it's possible for a note's duration to end with a barline (since it can include them and there is no rule saying it can't end with one). We should probably make both of those invalid, for consistency and to avoid confusion.

**Comment by elyisgreat** [comment]
Agreed. this would support the philosophy that baronies are *events*, and not event separators. However there is still the issue of #97. I think we can get around this by allowing a `~` preceding a note to indicate that it is the continuation of a tie.

**Comment by daveyarwood** [comment]
Do you mean that this should be valid?

```
c1~|1~|1
```

Because it is :)  Maybe I'm misunderstanding your point.

**Comment by elyisgreat** [comment]
It doesn't make sense to me that `c1| d` is invalid but `c1|~1 d` is valid because of the tie.

**Comment by daveyarwood** [comment]
That goes back to the exception I mentioned above, where it is OK to leave out spaces between barlines if the barlines are mixed in with a note's duration.

In this case, the parser sees `c1|~1 d` as "C note, whitespace, D note" -- in other words, two events separated by whitespace. The C note just happens to contain a barline because its duration is two whole notes tied across a barline.
