### ISSUE TITLE
Guitar Tabs

### ISSUE THREAD

**Issue by rwatts07** [alda-lang/alda#216]
I've been playing around with Alda a bit recently and thought it would be nice if I could use it for writing guitar tabs.  For example a syntax along the lines of:

```
midi-electric-guitar-clean "Intro":
e: x x 0 x x x 2 2
B: x x 0 x x x 2 2
G: x x 0 x x x 0 0
D: 2 2 x 0 0 0 x x
A: 2 2 x 2 2 2 x x
E: 0 0 x 3 3 3 x x
```

I started kicking this around some with the idea that each string would be a voice with its note assigned based on the tuning (e.g. `E: 0` on the bottom string translates to `V0: o2 e`).  The fret numbers could translate to a number of `+`s to apply to the note, and `x` would just be a rest.  The above would translate to something like:

```
midi-electric-guitar-clean:
V1: o4 r r e r r r e++ e++
V2: o3 r r b r r r b++ b++
V3: o3 r r g r r r g g
V4: o3 d++ d++ r d d d r r
V5: o3 a++ a++ r a++ a++ a++ r r
V6: o2 e e r e+++ e+++ e+++ r r
```

I started writing some macros to generate `alda-code` expressions, but thought I'd ask here in case I'm on the wrong track.

**Comment by daveyarwood** [comment]
This is a great idea! #182 touched on this too. I like your syntax ideas, and feel like I would definitely use this.

A big item on our TODO list is a plugin system (see issue https://github.com/alda-lang/alda/issues/37) -- this is the way I would prefer for things like this to be implemented, rather than adding them to the Alda language itself.

See #37 for my thoughts on how we could implement a plugin system. Basically we'll let people write their own programs (in any language) that read in the score file and perform transformations on the text. In this case, it could be as simple as transforming something like this:

```
A: 2 2 x 2 2 2 x x
E: 0 0 x 3 3 3 x x
```

into something like this:

```
V5: o2 b b r b b b r r
V6: o2 e e r g g g r r
```

Then we could set up some system where we fetch the programs from GitHub repos and use them to transform the score into valid Alda syntax before parsing it.

The great thing is that the guitar tab syntax could be implemented in multiple different ways, and score-writers could use whichever Alda guitar tab plugin they prefer.

If you're interested in pushing forward with this, I think it wouldn't be too difficult to take an initial stab at #37. I'll be happy to help!

**Comment by rwatts07** [comment]
I like the plugin system idea.  Since the tabs can be represented as alda code I think it makes sense to just have a translation step in between rather than messing with the alda parser itself.  I'll take a look at #37 and see what I can do there.

**Comment by daveyarwood** [comment]
Closing this for now -- definitely interesting in seeing where this goes, though!
