### ISSUE TITLE
long comment syntax number error

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#230]
I tried to leave this as a comment

`(comment alda 1.0.0rc16)`

but it threw a syntax error. There is nothing wrong here, but it's being interpreted as if it's a number and has to be formatted. Note how this comment doesn't throw an error:

`(comment alda 1.0)`

**Comment by daveyarwood** [comment]
The issue here is that `(comment alda 1.0.0rc16)` is not valid Clojure syntax. The Clojure parser doesn't know what to do with `1.0.0rc16` because it isn't valid syntax.

What happens when you type `(comment "comment here")` in an Alda score is the same as if you were to type the same thing into a Clojure source file. In Alda, anything between parentheses is parsed as a Clojure expression.

In Clojure, the `comment` macro simply ignores all of its arguments, so it doesn't matter what they are. The only thing is, the syntax must still be valid. That means you can make a comment out of any number of valid Clojure expressions. Some examples of valid Clojure expressions are:

* symbols, e.g. `alda`
* strings, e.g. `"hello there I'm a string"`
* keywords, e.g. `:keyword`
* numbers, e.g. `1`, `1.0`, `1/1`
* expressions, e.g. `(println "hey!")`
* vectors of things, e.g. `[1 2 3 "foo" :bar (+ 1 1)]`

For long comments in Alda scores, I would recommend using strings, i.e. `(comment "alda 1.0.0-rc16")`

**Comment by elyisgreat** [comment]
Yeah. I figured that this was a clojure error and not an Alda error. All the more reason why Alda needs its own long comment syntax... :/

**Comment by daveyarwood** [comment]
I think we will have to agree to disagree on a native long comment syntax, at least for now.

My take on it is still that short comments are easier to work with (especially with a lot of text editors having good support for easily commenting/uncommenting lines), so I don't think that Alda especially needs a long comment syntax at all, especially given that Clojure's `comment` macro can be used as a sort of compromise.
