### ISSUE TITLE
Weird server restart issue

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#234]
Occasionally, when I try to restart the server, it just hangs there and doesn't restart.

![server not restarting](https://cloud.githubusercontent.com/assets/8622264/15630253/4e1e82b8-2500-11e6-94ee-13ad4e19397b.png)

Like, at all
![server still not restarting](https://cloud.githubusercontent.com/assets/8622264/15630255/59d4fcb8-2500-11e6-807e-1791b46d907f.png)

I have to restart my computer to get the server to restart. I've been informed that the server always shuts down upon system restart, so I don't know what's going on here.

**Comment by daveyarwood** [comment]
I'll leave this issue open for now until we can determine the exact cause.

As a workaround, if you ever have any problems getting an Alda server to shut down, you can find and kill the process manually:

1. Find the process ID (pid):

        $ ps aux | grep alda
        dave            17499   4.7 11.1  8345404 1855940   ??  S     6:57PM   1:14.70 java -Dclojure.compiler.direct-linking=true -jar /usr/local/bin/alda --host http://localhost --port 27713 --pre-buffer 0 --post-buffer 1000 --alda-fingerprint server
        dave            18219   0.0  0.0  2432784    632 s000  S+    7:02PM   0:00.00 grep alda

    `ps` is a Unix program that lists all of your system's running processes along with their process IDs and other information. It's common to use `ps` and pipe the results to `grep` in order to print the info for only the lines that contain a search string.

    In this case, 17499 is the pid of the Alda server I have running, and 18219 is the current `grep` process, so 17499 is the process I want to kill.

2. Kill the Alda process:

        $ kill -9 17499

    When you run `ps aux | grep alda` again, you can see that the process was killed.

**Comment by elyisgreat** [comment]
Still happening in 1.0.0rc23

**Comment by elyisgreat** [comment]
confirmed for 1.0.0rc31

**Comment by daveyarwood** [comment]
@elyisgreat As of 1.0.0-rc32, the Alda server is a ZeroMQ port instead of an HTTP server, which might solve this issue. I'd be curious to know if you're still seeing it.

**Comment by elyisgreat** [comment]
So far no. It still sometimes says "server down" even when it isn't. I'm not sure if it is still happening.

**Comment by daveyarwood** [comment]
@elyisgreat Does 1.0.0-rc35 solve this issue?

**Comment by elyisgreat** [comment]
Not sure. This is what happened when trying to restart the server in rc35

```
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda downup
[27713] Server already down.

[27713] Starting Alda server...
[27713] Server up ✓
[27713] Starting worker processes...
[27713] ERROR java.io.IOException: Too many open files in system
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda downup
[27713] Stopping Alda server...
[27713] Server down ✓

[27713] Starting Alda server...
[27713] Server down ✗
Elys-Computer-Mac-OS-Edition:~ elygolden$ 
```

**Comment by daveyarwood** [comment]
So it looks like 4 workers may be too much for your system to handle. (I tried 6 on my 2014 Macbook Pro and got that same error.)

Try force-killing all alda processes with `pkill -9 -f alda-fingerprint`, and trying again with only 1 or 2 workers: `alda -w 2 up` and see if that works better?

**Comment by elyisgreat** [comment]
yep. seems to work much better.
```
Elys-Computer-Mac-OS-Edition:~ elygolden$ pkill -9 -f alda-fingerprint
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda status
[27713] Server down ✗
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda -w 2 up
[27713] Starting Alda server...
[27713] Server up ✓
[27713] Starting worker processes...
[27713] Ready ✓
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda status
[27713] Server up (2/2 workers available)
Elys-Computer-Mac-OS-Edition:~ elygolden$ 
```
The weird thing is that for 4 workers it still starts up the server; It's just that the workers start up after the error is thrown.
```
Elys-Computer-Mac-OS-Edition:~ elygolden$ pkill -9 -f alda-fingerprint
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda -w 4 up
[27713] Starting Alda server...
[27713] Server up ✓
[27713] Starting worker processes...
[27713] ERROR java.io.IOException: Too many open files in system
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda status
[27713] Server up (1/4 workers available)
^[[AElys-Computer-Mac-OS-Edition:~ elygolden$ alda status
[27713] Server up (3/4 workers available)
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda status
[27713] Server up (3/4 workers available)
Elys-Computer-Mac-OS-Edition:~ elygolden$ alda status
[27713] Server up (4/4 workers available)
Elys-Computer-Mac-OS-Edition:~ elygolden$ 
```

**Comment by daveyarwood** [comment]
Awesome! This makes me wonder if maybe the default number of workers should be 2 instead of 4... that way you would get something that works out-of-the-box, and if you want, you can opt into more workers.

So it actually looks like it's working with 4 workers, they just consume too many resources or something as they're starting up. I can do some research on that and see if I can figure it out. I did notice that my computer fan spins briefly as the workers are starting up, and if I watch in the Activity Monitor, I can see the 4 `java` processes at 100%+ CPU just briefly. Maybe there is some way we can make them use less CPU as they're starting up...

**Comment by daveyarwood** [comment]
Likely related: https://github.com/zeromq/jeromq/issues/183

**Comment by daveyarwood** [comment]
@elyisgreat Out of curiosity, what is the output of `ulimit -n` on your computer? (This is the available number of "open files")

**Comment by elyisgreat** [comment]
```
Elys-Computer-Mac-OS-Edition:~ elygolden$ ulimit -n
256
Elys-Computer-Mac-OS-Edition:~ elygolden$ 
```

**Comment by daveyarwood** [comment]
I think that might explain why you're running into problems with 4 workers. Reading up on this a little more, it seems that the default `ulimit` for a lot of Mac users is 256, which is on the low side for an application like Alda that needs to use a lot of connections.

Something to try would be to run `ulimit -n 10000` followed by `alda downup` in the same terminal. This would set the open files limit to 10,000 instead of 256 for the current terminal session. (If you open another terminal and run `ulimit -n`, you'll see that your limit is back to 256.)

If that works well, then there are ways of keeping your `ulimit` set to a higher number. The Riak documentation has some really good info on how to do that: https://docs.basho.com/riak/kv/2.1.4/using/performance/open-files-limit/

I am looking into ways to use less connections, too, so people don't run into this problem as easily. I have a hunch that the connection-managing parts of the Alda codebase are not as efficient as they could be.

**Comment by elyisgreat** [comment]
Perhaps. Although that still doesn't explain the original restart issue I was having. So far I haven't encountered it, however idk if it's fixed.

**Comment by daveyarwood** [comment]
I think we can consider the original issue fixed -- I think it had to do with the server being an HTTP server. I think the new server implementation with ZeroMQ sockets is less error-prone, so that when you run `alda down`, it is much more likely to get the server to shut down.

Shall we close this issue for the time being? We can always re-open it if you start noticing it happening again with the new server format.

**Comment by elyisgreat** [comment]
No problem. Also glad the other issue is now separate.
