### ISSUE TITLE
Attribute default

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#237]
In 1.0.0rc15, it was fixed so that local attributes properly override global attributes. Now, in issue #199 I mentioned the possibility of a `default` value that would set the value of a local attribute back to the global default (if used on a global attribute it could be used to revert it to a "system default"). This was initially rejected, however with the implementation of local over global overriding I thought I would suggest again the idea. Thoughts?

**Comment by daveyarwood** [comment]
I'm still leaning against that idea. I'm not sure what the use case would be. Can you think of an example of where it might be useful?

I also still like [the idea I had](https://github.com/alda-lang/alda/issues/199#issuecomment-194107105) where variables could be used for this kind of thing:

```
defaultVolume = (volume 75)
quieter = (volume 50)
louder = (volume 100)

piano:
  defaultVolume c8 d e f g2
  quieter c8 d e f g2
  louder c8 d e f g2
  defaultVolume > c2
```

**Comment by daveyarwood** [comment]
I just had another idea 💡  This is something that should already work, so you don't have to wait for variables to be implemented. You can use inline Clojure code to sort of "roll your own" attributes:

```
(defn default-volume [] (volume 75))
(defn quieter [] (volume 50))
(defn louder [] (volume 100))

piano:
  (default-volume) c8 d e f g2
  (quieter) c8 d e f g2
  (louder) c8 d e f g2
  (default-volume) > c2
```

What's happening here is, I'm defining functions that, when called, just set the current instruments' volume to a particular value. Then I'm calling them whenever I want that to happen.

**Comment by elyisgreat** [comment]
that's a clever way to implement defaults. I'm still curious though how the mechanics work now with the local properly overriding global.

**Comment by daveyarwood** [comment]
I basically just changed the order that attributes are applied.

So, under the hood, this is how global attributes have always worked:

1. The score evaluator reaches a global attribute like `(tempo! 180)`. It makes a note of the current offset into the score (in milliseconds) and the attribute and value to apply at that point. It stores these in a simple key-value store of offsets to global attribute changes that should occur at that point in time.

2. Every time an instrument part moves forward (i.e. each time it has a note or a rest), the score evaluator checks between where the instrument was before and where it is now and determines if there are any global attributes to apply during that interval. If there are, the attributes get applied to the instrument.

This was broken before because if you had something like this:

```
(tempo! 180)

piano: (tempo 120) c
```

Before, the order of operations was:

* Apply global attributes at beginning of instrument part. Piano tempo is now 180.
* Piano sets its tempo to 120.
* We're about to play a note, so apply global attributes again. Piano tempo is 180 again.

The fix was to apply global attributes at the beginning of each instrument part, and **after** each note/rest, not before. So the corrected order of operations is:

* Apply global attributes at beginning of instrument part. Piano tempo is now 180.
* Piano sets its tempo to 120.
* Piano plays a C, bumping its current offset by 500 ms.
* Apply global attributes. Piano isn't at the beginning of the score anymore, so the "tempo 180" global attribute doesn't apply. Piano tempo is still 120.

**Comment by daveyarwood** [comment]
@elyisgreat Hope you don't mind if I close this issue. I do appreciate the suggestion, but I think anything we would implement would be about the same as using inline Clojure code to get the same behavior, and I like the inline Clojure way better because it's more flexible, allowing you to define exactly the behavior you want.
