### ISSUE TITLE
symphony

### ISSUE THREAD

**Issue by goog** [alda-lang/alda#239]
I'm a programmer who don't know how to music, i wanna know whether the **alda** could compose a symphony?

**Comment by elyisgreat** [comment]
That's actually a good question. Symphonies require a lot of instruments and a large file. Currently large files will not evaluate (see #235). However I'm not sure about instrument instances. @daveyarwood how many instrument instances are currently allowed per score?

**Comment by daveyarwood** [comment]
Hi @goog - are you asking if Alda could generate a symphony on its own? If so, I think the answer is "maybe" -- you could write a bunch of functions with inline Clojure code that would randomly/probabilistically generate motifs and string them together in interesting ways, and use that to form the building blocks of a symphony. That would be rather complicated, though.

If you're asking if Alda is a suitable platform for composing a symphony, I would say "yes," but with the caveat that it's still beta-level software and there are some kinks to work out:

- As @elyisgreat mentioned, very large score files will trigger a "Method code too large!" Java error. I think we'll be able to solve that issue, but currently it is one limitation.

  One way to get around this is [modules](#133), which are not implemented yet, but once they are, they'll allow you to take a huge score and break it down into separate files that the Alda compiler can handle. A symphony score might look something like this:

      # score.alda

      (load-module "violin.alda")
      (load-module "viola.alda")
      (load-module "cello.alda")
      ...
      ...
      ...
      (load-module "tuba.alda")
      (load-module "timpani.alda")
      (load-module "percussion.alda")

  Each call to `load-module` would separately parse and evaluate a file containing an instrument part and add it to the score.

  I'm still committed to fixing the "Method code too large!" issue so that score writers can still create large score files if they want to, but I figured it was worth mentioning the planned modules feature, as it's something I would recommend using anyway, as a way of better organizing your code if you were to write a big piece like a symphony.

- There is no limit to the number of instrument instances you can have in an Alda score, _but_ due to restrictions in the General MIDI spec (which the Java MIDI system follows), a MIDI synthesizer has only 16 channels, and an Alda score uses one channel per instrument part, so an Alda score is limited to 16 MIDI instruments.

  I've thought about [some ways to work around this](#178), and I think it is probably possible to support using multiple MIDI synthesizers in a single Alda score, which would allow you to use more than 16 MIDI channels in a score.

**Comment by goog** [comment]
@daveyarwood I mean the second one, thanks for your interdisciplinary contribution! nice work :+1:

**Comment by daveyarwood** [comment]
:)
