### ISSUE TITLE
Not all instruments play in the correct key

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#245]
Consider the following:

```
piano: c d e f g r
trumpet: [r]*6 c d e f g r
glockenspiel: [r]*12 c d e f g r
```

What I expected was the identical notes played in succession by each of the different instruments. However the glockenspiel actually played the notes five semitones above the written values. I have not yet found any other instruments that exhibit this, however it is possible that there are.

From my understanding there are no transposing instruments in alda, as there will be many attributes and operators that will handle it. So I am guessing that this is a bug.

**Comment by daveyarwood** [comment]
This isn't a bug -- some General MIDI instruments such as the glockenspiel contain additional partials in order to emulate the sound of the actual instrument. If you listen really closely to the glockenspiel, you can hear the notes `c d e f g` -- they are just buried underneath additional partials. Alda isn't doing anything to tune certain instruments differently than others, if that's what you're wondering.

**Comment by elyisgreat** [comment]
Interesting. Playing it again I do hear the original notes, however the raised notes are much more dominant. what other instruments does this apply to?

**Comment by daveyarwood** [comment]
> however the raised notes are much more dominant (or I guess subdominant 😛)

_rimshot_

> what other instruments does this apply to?

I'm not sure, offhand, but I wouldn't be surprised if some of the other metallic percussion instruments and "synth effect" instruments had similar behavior.
