### ISSUE TITLE
Refining variables

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#246]
I noticed that variables were finally implemented in the latest release of alda. However with the new note spacing rules I find that writing is much more restrictive. Thus, I suggest a literal for variables; that way the note spacing rules can be more relaxed, however variables would still be clearly marked. A single quote literal `'<variable>'` is a possibility, as well as having something like a character before a variable `'<variable>` to indicate that it is one (similar to markers), however I would like to hear other suggestions.

**Comment by elyisgreat** [comment]
I should also mention that it restricts spacing of not just notes that are valid variable names (`cde`,`cde8f`), but also adjacent event blocks `[c d e f][g a b > c <]`, clojure expressions `(vol 90)(quant 90)`, and octave steps `c >c< c` , which is why I think the literal or character marker is a better option for variables.

**Comment by daveyarwood** [comment]
I would rather avoid making a literal syntax for variables -- I like the cleaner feel of just the variable name by itself, even if it makes it a little more difficult to work around, when specifying the grammar.

I think it should be possible to adjust the grammar so that scenarios like the ones you mentioned are allowed, while still requiring spaces after notes. I'll play around with this and see what I can do.

**Comment by elyisgreat** [comment]
If you test the cases I provided, I only got an "Invalid Syntax" error when there was adjoining characters that did not make a valid variable name. otherwise nothing happened.

**Comment by daveyarwood** [comment]
That's a good point -- do you think an error should be thrown if you try to use a variable that hasn't been defined? Currently, the nonexistent variable is just ignored.

**Comment by elyisgreat** [comment]
It still sort of makes sense, after all if a variable hasn't been defined it has no value. for example `piano: blarg c d e` just plays `piano: c d e`.

**Comment by elyisgreat** [comment]
Also: for octave steps I did not get an error when it preceded the variable name `c >c <c`, or when two were directly adjacent to each other `c >> c << c`, however if they were different types, such as in `c >< c`, there was an error.

**Comment by elyisgreat** [comment]
And if this issue is going to be "enchanting variables" let's not forget about naturals...

**Comment by daveyarwood** [comment]
I could easily throw in an alternate natural syntax... the question is, what should it be? :)

**Comment by elyisgreat** [comment]
What were the previously discussed options?

**Comment by daveyarwood** [comment]
I think ``` ` ``` and `_` are the two viable options so far... I'm leaning towards `_`, but would be open to other ideas. There are still other symbols we haven't used yet, like `^`, `&`, `\`...

**Comment by elyisgreat** [comment]
I still like `º` (U+00BA) even though it's not ASCII (I type it on Mac using option+0 and I think on PC alt+0 will do it). I personally prefer ````` as it looks more like `º` and is not a valid variable name.

**Comment by daveyarwood** [comment]
The more I read about the backtick, the more I think it's a bad idea to use it as a syntactic feature of a language that I want to be widely used. It can apparently cause weird quoting issues, and I read that some international keyboards don't have a key for it. I think the more we stick to commonly used (and easily typed) ASCII characters, the better off we'll be. So, I'm going to go with underscore for now.

**Comment by elyisgreat** [comment]
Problem with underscores is that they are valid variable name characters. I guess it's not a huge problem, but `+` and `-` are not so it might be easier consistency wise.

**Comment by daveyarwood** [comment]
But variables must start with two letters, so there is no conflict :)

**Comment by elyisgreat** [comment]
Finally the natural debate is over. I'm wondering about the invalid syntax errors, what is causing them in the cases that I provided?

**Comment by daveyarwood** [comment]
I was a little overzealous with the grammar changes I made to enforce spaces between notes -- I made it so that at least one space (or newline) is required between ALL events, which includes octave changes, notes, event sequences, Clojure code expressions, etc.

I think I do want to enforce space between all events, but with the notable exception of the octave up/down operators, which I think should be OK to append or prepend to a note, e.g. `>c`, `>c<`, `c<`.

Can you think of any other cases where it should be acceptable to not have space between events? I'm not sold on back-to-back event sequences, but maybe you have a use case in mind?

**Comment by daveyarwood** [comment]
> It still sort of makes sense, after all if a variable hasn't been defined it has no value. for example `piano: blarg c d e` just plays `piano: c d e`.

It just occurred to me that you could use this as a hacky way to embed comments into your score :P 

```
piano:
  this is valid alda syntax
  c8 d e f g

  as long as every word starts with at least two letters
  and you dont use punctuation
  a b > c
```

I'm kind of OK with this.

**Comment by elyisgreat** [comment]
Not a huge fan of that, but it doesn't really matter. After all the definition of undefined variables simply being nothing still holds.

**Comment by daveyarwood** [comment]
¯\\\_(ツ)\_/¯

**Comment by elyisgreat** [comment]
For whitespace cases, I don't see a need to require spaces between clojure expressions; `(vol 90)(quant 90)` doesn't look any dirtier than `(vol 90) (quant 90)`, yet it's more difficult to write. For event sequences, I used it back to back in this case:

`V2: [o4 r4. e4. e8 r8]*2[o4 r4. a-4. a-8 r8]*2[o4 r4. a4. a8 r8]*2 r1~1`

There's no reason to separate them, as the only change is stylistic.

Don't forget slurs such as `g~a~b`, which isn't a valid variable name, but may be stylistically desirable.

Personally I think the spacing syntax should apply only when the string of notes makes a valid variable name.

**Comment by daveyarwood** [comment]
I definitely see where you're coming from -- it would be nice to have the flexibility to leave the spaces out, if that's your preference. But from a language design perspective, I would like to start imposing a restriction that events (with the exception of `<` or `>` before/after a note) be separated by at least one space.

Three reasons for this:

* It makes the grammar simpler, therefore easier to work with from a development standpoint.
* The simpler grammar means less potential for parsing conflicts.
* It will make Alda code look cleaner / less cluttered if all distinct events are separated visually by spaces by necessity.

**Comment by daveyarwood** [comment]
By the way, I just pushed a [new release](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc22) that fixes the issue with `<` or `>` after a note not being considered valid, and changes the variable syntax from `=` to `_`.

**Comment by elyisgreat** [comment]
I noticed. `c >< c` still throws an error though. I understand for other events, however I also think clojure expressions should be an exception, especially considering that clojure code generated from `alda parse` throws a syntax error when played.

**Comment by daveyarwood** [comment]
Oh, good catch! I'll fix that shortly.

Also, this is totally off-topic, but your code snippet `V2: [o4 r4. e4. e8 r8]*2 [o4 r4. a-4. a-8 r8]*2 [o4 r4. a4. a8 r8]*2 r1~1` could also be expressed like this using inline Clojure code and the `alda-code` function:

```
V2:
  (for [x ["e" "a-" "a"]]
    (alda-code (format "[o4 r4. %s4. %s8 r8]*2" x x)))
```

The idea is to re-use similar snippets of code, and just change the part that changes each time (i.e. in this case, the note). So this `for` loop generates 3 strings of Alda code, one for each note, and each string is `"[o4 r4. %s4. %s8 r8]*2"` with the `%s` replaced by the current note.

I imagine we could make this even cleaner looking, but it's at least interesting to think about.

**Comment by elyisgreat** [comment]
Although I should mention the clojure generated from `alda parse` throws a syntax error in rc20 as well. Not quite sure what is going on there.

**Comment by daveyarwood** [comment]
Hmm... you're right, code generated by `alda parse` doesn't play when pasted directly into an Alda score. I can explain why:

```
$ alda parse -c 'bassoon: o3 [c d]*4'
(alda.lisp/score
 (alda.lisp/part
  {:names ["bassoon"]}
  (alda.lisp/octave 3)
  (alda.lisp/times
   4
   [(alda.lisp/note (alda.lisp/pitch :c))
    (alda.lisp/note (alda.lisp/pitch :d))])))
```

An Alda score is required to contain at least one instrument part. So if I put the following into a text file:

```
(alda.lisp/score
 (alda.lisp/part
  {:names ["bassoon"]}
  (alda.lisp/octave 3)
  (alda.lisp/times
   4
   [(alda.lisp/note (alda.lisp/pitch :c))
    (alda.lisp/note (alda.lisp/pitch :d))])))
```

and then try to play it, it will fail with "Invalid Alda syntax" because it isn't finding anything like `bassoon:` in the file. To the parser, the code I pasted in is valid as a "header" because I could be using Clojure to define functions, etc. that I might want to use in my instrument parts. The parser doesn't actually care what the Clojure code is doing, it just sees a bunch of Clojure syntax and says "OK, this is a Clojure expression, great. Now I'm expecting at least one instrument part!"

So the immediate problem can be solved by adding a "dummy part" at the end:

```
(alda.lisp/score
 (alda.lisp/part
  {:names ["bassoon"]}
  (alda.lisp/octave 3)
  (alda.lisp/times
   4
   [(alda.lisp/note (alda.lisp/pitch :c))
    (alda.lisp/note (alda.lisp/pitch :d))])))

piano:
```

When I try to play this score, it parses successfully, but then I get a different error:

```
$ alda play -f /tmp/code.alda
[27713] ERROR Invalid event: {:chord-mode false, :current-instruments #{"bassoon-mLyWz"}, ...
```

The issue here is that `(alda.lisp/score ...)` is not intended to be used inside an Alda score -- it returns a full score itself, instead of returning something that the Alda score evaluator recognizes as an event, so it throws an "Invalid event" error.

If you pull out just the `(alda.lisp/part ...)` part of the score, i.e. delete `(alda.lisp/score` and then the last `)`, then it works.

This works:

```
(alda.lisp/part
 {:names ["bassoon"]}
 (alda.lisp/octave 3)
 (alda.lisp/times
  4
  [(alda.lisp/note (alda.lisp/pitch :c))
  (alda.lisp/note (alda.lisp/pitch :d))]))

piano:
```

I'm not sure if pasting the results of `alda parse` into a file and trying to play it is a behavior we want to support. In my mind, it doesn't really make sense to paste an entire score inside of another score. I do think that pasting invidual `part`s, `note`s, etc. from `alda parse` output is a good thing to support (and we do), as it allows you to play around with Alda events at a lower level, and learn how Alda's Clojure DSL works. One thing we could do is make it acceptable for a score to just be a header, so you don't need to include a dummy instrument part in order to get something like the above to parse.

**Comment by elyisgreat** [comment]
Hm. perhaps the requirement can be changed so that it requires either one instrument part or a clojure expression. Also, what is your stance between requiring spaces between clojure expressions? I get your stance for other events, however I'm not sure how it applies to inline clojure code.

**Comment by daveyarwood** [comment]
I'm in favor of requiring spaces between Clojure expressions. In a Clojure program, it's not required (i.e. `(+ 1 1)(+ 2 2)` is valid), but on the other hand, I've never seen two separate S-expressions back-to-back without space in between, so it definitely feels weird to see it that way. In Alda, a Clojure expression typically represents a distinct entity (e.g. a note or a list of notes), so in my mind, it makes sense to require them to be separated by spaces.

**Comment by elyisgreat** [comment]
I was thinking in the context of attribute-setting, as I'm not proficient with clojure. I don't see any reason to use `(vol 90) (quant 90)` as opposed to `(vol 90)(quant 90)`. Also, it seems weird that clojure code within alda would have different syntactical rules from regular clojure code.

**Comment by daveyarwood** [comment]
I understand and agree to some degree, but my reasoning for wanting to require spaces between almost all events goes back to the three reasons I noted above -- simpler grammar, less parsing conflicts, better-looking (in my eyes) code.

**Comment by elyisgreat** [comment]
I suppose. Although I think the requirement for 1 instrument part should be changed to 1 clojure expression OR 1 instrument part (or removed entirely).

**Comment by daveyarwood** [comment]
Just pushed out another release, [1.0.0-rc23](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc23) -- it fixes the bug with `c >< c`, and it also makes it so that just Clojure expressions is a valid score.

I'm going to close this issue for now -- think we've gotten a lot of work done today :)

Thanks for pointing out these issues so I can fix them, or at least think about them! If you don't mind, in the future if you have any quick suggestions or questions, the [Clojurians Slack](http://clojurians.net) is a good place for that -- you can ping me by typing`@dave` in the `#alda` channel there, I'm usually around if I have a computer handy! 💻

**Comment by elyisgreat** [comment]
looks like it's throwing an error now for undefined variables in rc24. Not sure if you want it like that or not. Your call really.

**Comment by daveyarwood** [comment]
Yeah, I decided to throw an error for undefined variables. I don't think
there is any use case where you would want to use a variable that hasn't
been defined, and if you do it by mistake, it's best that you know as soon
as possible :)

**Comment by elyisgreat** [comment]
sounds good. you should probably document the change though.
