### ISSUE TITLE
Improve instance/group assignment + "." group-member operator

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#249]
Consider the following code:

```
piano:
piano "piano1":

piano: o4 c d e f g a b > c
piano1: o4 e f g a b > c d e
```

When played, it plays normally. However, if I switch the declaration of the instruments at the top

```
piano "piano1":
piano:

piano: o4 c d e f g a b > c
piano1: o4 e f g a b > c d e
```

`piano1` does not start playing until `piano` has finished its melody. The order of the melodies at the bottom does not matter, so 

```
piano "piano1":
piano:

piano1: o4 e f g a b > c d e
piano: o4 c d e f g a b > c
```

will play `piano1` first and then play `piano`.

And if they're both named, there is no problem. both of the scores below play normally.

```
piano "piano1":
piano "piano2":

piano1: o4 c d e f g a b > c
piano2: o4 e f g a b > c d e
```

```
piano "piano2":
piano "piano1":

piano1: o4 c d e f g a b > c
piano2: o4 e f g a b > c d e
```

**Comment by daveyarwood** [comment]
This is working as expected. [The rules of instance and group assignment](https://github.com/alda-lang/alda/blob/master/doc/instance-and-group-assignment.md) are a bit complicated, but I feel like they should hopefully work the way one might expect. The question is, what do/should one expect?

To explain what's happening in each of the above scenarios:

---

Example 1:

```
piano:
piano "piano1":

piano: o4 c d e f g a b > c
piano1: o4 e f g a b > c d e
```

`piano:` registers "piano A." Then `piano "piano1"` contains a nickname, so it is forced to be a new instrument, "piano B."

---

Example 2:

```
piano "piano1":
piano:

piano: o4 c d e f g a b > c
piano1: o4 e f g a b > c d e
```

`piano "piano 1"` registers "piano A," then `piano:` does not contain a nickname, so it is interpreted to be the first instance it finds that is a piano, so it ends up also being piano A.

---

Example 3:

```
piano "piano1":
piano "piano2":

piano1: o4 c d e f g a b > c
piano2: o4 e f g a b > c d e
```

Now both piano instances are named, so they are both forced to be new instances.

---

This makes perfect sense to me, but I admit that's quite complicated, and might not make perfect sense to other people who use Alda. I can understand how in Example 2, one might expect "piano" to be available again as a new instrument instance after you named another piano, but the question is, is that the way it _should_ work?

**Comment by elyisgreat** [comment]
The way I expected it was that an unnamed instrument was treated as its own instrument instance that was just called by the name of the instrument itself. so in the case of the code

```
piano "piano1":
piano:

piano: o4 c d e f g a b > c
piano1: o4 e f g a b > c d e
```

what I expected was that `piano` was its own instrument (simply called "piano") and that `piano1` was a separate piano called "piano1".

But what happens when we modify the code slightly?

```
piano "piano1":
piano "piano2":
piano:

piano: o4 c d e f g a b > c
piano1: o4 e f g a b > c d e
piano2: o4 g a b > c d e f g
```

According to my expectations, all these instruments would play together. However, with the way things are now there's ambiguity as to which piano `piano` refers to, and if you actually run this, it plays `piano` and `piano2` together, followed by `piano1`. To me, this makes no sense, and I think it's better to treat instruments without nicknames as if they're named what they are.

**Comment by daveyarwood** [comment]
Yeah, that does make a lot of sense. I think we should change it to make it
work the way you're describing before the release of 1.0.0. The more
intuitive / less confusing we can make it, the better!

**Comment by elyisgreat** [comment]
I am going to refine my expectations into the following logic. I think it should be pretty intuitive, although I'd love to hear your thoughts on it

an instrument call takes the form `$type "$name": ` or the form `$argument: `

If the call has two arguments then
  If it is the first call with the arguments `$type` and `$name` then 
    If there is an existing instrument with name $name then throw a syntax error 
    else create a new instrument instance of type `$type` with name `$name`
  else treat the call as a continuation of the instrument with name `$name`

If the call has one argument then
  If it is the first call of an instrument with the name `$argument` then
  create a new instrument instance of type `$argument` (will throw an error if type `$argument` is not a valid type) with name `$argument`
  else treat the call as a continuation of the instrument with name `$name`

**Comment by daveyarwood** [comment]
Makes sense to me! :+1:

**Comment by elyisgreat** [comment]
Ok. I changed the blocking a bit to make it more readable.

**Comment by daveyarwood** [comment]
OK, so, after re-familiarizing myself with the code... One wrinkle about doing it the way you're proposing is that it would make it cumbersome to define new named instrument groups using all new instrument instances.

The way it works currently:

- Let's say we already have a clarinet and a flute in a score. Let's call them clarinet-1 and flute-1:

  ```
  clarinet "clarinet-1": c8 d e f
  flute "flute-1": c8 d e f
  ```

- Now let's say we want to create a _new_ clarinet and a _new_ flute, and let's say a (new) oboe too, and we want them to be in a group together, and we don't care about ever using them separately. Let's call this group "winds":

  ```
  clarinet/flute/oboe "winds": c1/e/g
  ```

  Because an alias is being assigned to the group, a new instance is created for every stock instrument. So we end up with essentially clarinet-2, flute-2 and oboe-1, all new, anonymous instances in a named group.

If we made this change:

- Trying to create a new, named group with new, anonymous instrument instances, does not work. Following the example above, if we tried to instantiate the group with `clarinet/flute/oboe "winds":`, we would end up re-using the existing clarinet and flute, which is not the behavior I would expect.

- Instead, we would be forced to explicitly create a new clarinet and a new flute, resulting in this rather awkward-looking code:

  ```
  clarinet "clarinet-2":
  flute "flute-2":
  clarinet-2/flute-2/oboe "winds": c1/e/g
  ```

It's been a long time (years!) since I designed this system of instance assignment, but I believe this may have been my reasoning for making it work the way it does. Basically, the idea is that a "stock instrument" like `clarinet` is always reusable as a way to initialize a new instance of that instrument in a group.

**Comment by elyisgreat** [comment]
Oh. I must admit I completely forgot about grouped instruments. I think for ungrouped instruments the logic I'm proposing makes the most sense. 

This, however is the problem:

>A new instance of an instrument is created whenever a **stock instrument** is called with any nickname, either as part of a group or not.

This makes it very easy to make new instances of stock instruments within groups. There are problems with this, though, besides having a less intuitive instrument system. 

1. You can't separate new instances of stock instruments created in groups. Consider:

```
clarinet: c8 d e f
flute: c8 d e f
clarinet/flute/oboe "winds": c1/e/g
```

This creates a new clarinet and flute, but what if you want to extract just the clarinet? There's no way to refer to it unambiguously. 

2. Recall that you can name instruments after other stock instruments. I'd imagine this is highly recommended against, however my proposed system would have no problem handling it. This creates a problem, though, because if one *were* to do something like this...

```
piano "violin": c d e f g
piano "clarinet": c d e f g
violin/clarinet "pianos": c/e/g
```
They would expect that no new instrument instances are created. But they would end up with a violin and a clarinet that they did not want. 

Personally, I think it's more intuitive that instrument grouping does not create new instances, as I see it more as bringing instruments together. However I can see why it may be desirable to have new instances.

**Comment by jimcheetham** [comment]
Separating instruments from a group could be achieved, if the implicit instrument name were a mix of the group name plus the instrument.

e.g. `clarinet/flute/oboe "winds":` creates
* clarinet "winds-clarinet":
* flute "winds-flute":
* oboe "winds-oboe":

The second issue, where explicit names are created that might match implicit names, is a matter for the score writer. If you declare any instrument called "piano", any declaration of a new instrument with the same name should throw an error - whether that new declaration were implicit or explicit. The error helps the score writer discover what they've done wrong :-)

piano "violin": a b c
violin: a b c 
** Error, cannot create "violin:", an instrument with the name "violin" has already been declared

violin: a b c
piano "violin": a b c
** Error, cannot create "piano "violin":", an instrument with the name "violin" has already been declared

piano "winds-piano": a b c 
piano/clarinet "winds": a b c
** Error, cannot create "piano/clarinet "winds":", an instrument with the name "winds-piano" has already been declared

**Comment by elyisgreat** [comment]
Hm. I'm not a huge fan of either of those ideas; the first one because many stock instruments have a `-` character in their name, making it an ambiguous character in instrument calling. 

The second one is a problem because I don't believe we should disallow users from naming instruments after other instruments, mainly because in the future plugins will allow more instruments and this could break alda scores when played in a separate alda client that has those plugins.

I don't actually think it makes sense to ever create new instrument instances when grouping. when I think of grouping I think of bringing instruments together, not creating new ones. Unfortunately, this leads to some awkward code:

```
piano: c d e f g
piano/violin: c d e f g
#throws an error because violin must be a new instance
```

I don't know if someone would expect this. But it seems like the most intuitive behaviour to me.

**Comment by daveyarwood** [comment]
@jimcheetham said:
> Separating instruments from a group could be achieved, if the implicit instrument name were a mix of the group name plus the instrument.
>
> e.g. `clarinet/flute/oboe "winds":` creates
> * `clarinet "winds-clarinet":`
> * `flute "winds-flute":`
> * `oboe "winds-oboe":`

I like this idea. As @elyisgreat mentioned, there is some potential for naming conflicts, so I think what we would do is add a special operator for accessing members of a group. I think `.` might be a nice choice:

```
clarinet/flute/oboe "winds": c d e f

winds.clarinet: d  e f  g
winds.flute:    g  a b >c
winds.oboe:     b >c d  e
```

I like this because it provides the new ability of accessing (previously "anonymous") members of a named group, but still keeps the syntax concise and elegant.

---

I'm not sure yet what we should do (if anything) about the possibility of naming instrument instances after stock instruments and other instance names, but my gut feeling is that we should throw an informative error in both cases, like @jimcheetham said. I think that stock instrument names should always be available for creating new instances of that instrument, and if a score writer gives a name to an instance (or group of instances), then that name should always refer to that instance or group.

---

@elyisgreat: One important thing to remember is that when you use a group, e.g. `piano/violin:` it _will_ reuse instances if they already exist. Looking at your last example:

```
piano: c d e f g
piano/violin: c d e f g
```

This creates one piano and one violin. The piano plays `c d e f g c d e f g` and the violin plays `c d e f g`.

On the other hand, if you give a name to the group, the semantics are different; it will create _new_ instances for any stock instruments described in the group. Consider this score:

```
piano: c d e f g
piano/violin "piano-and-violin": c d e f g
```

This creates two pianos and one violin. The second piano was created in order to be a part of this new group, `piano-and-violin`.

Basically the idea is that if you're giving a name to a group, it's going to be its own entity with its own instrument instances, so as not to conflict with other instances that are doing their own thing.

This is my fault for not making it clearer in the documentation / examples, but my general recommendation is that you can't go wrong if you name every instrument and instrument group that you use, the first time you use it, and then use the names from then onward. Mixing and matching named and unnamed things is a recipe for confusion. So, continuing with the same example, take a look at this score:

```
piano "piano1": c d e f g
piano/violin: "piano2-and-violin": c d e f g
```

Like the last example, this also creates two pianos and one violin, but now it's extra clear that the first piano is a separate piano. Now from this point onward in the score, you are working with two separate entities, "piano1" and "piano2-and-violin," and it's easy to keep them separate in your mind as you're writing the score.

So then, what if you wanted to break the violin out of the "piano2-and-violin" group and have it play something by itself? If we added an operator, you would have an operator like `piano2-and-violin.violin` that you could use. Or, you could do something like this:

```
piano "piano1":
piano "piano2":
violin "violin1":

piano1: c d e f g
piano2/violin1 "piano2-and-violin1": c d e f g

violin1: a b > c
```

I know this is a little awkward-looking, but maybe this is a good example of a situation where a "member of group" operator could help make the code cleaner and more concise:

```
piano "piano1": c d e f g
piano/violin: "piano2-and-violin": c d e f g

piano2-and-violin.violin: a b > c
```

I'm still open to altering the way this works, it's just difficult to adjust such a complicated system. It might end up being easier to fix this issue with a combination of better documentation and useful error-throwing when score writers attempt to do things that aren't recommended.

**Comment by elyisgreat** [comment]
All this is just making the system even more complicated than it already is. I think we should use my system, and just disallow any new instances to be created as part of groups. Otherwise I think we need a new, simpler system.

**Comment by elyisgreat** [comment]
Now that I think about it, instrument instance calling needs to be not only refined, but completely overhauled. Alda will eventually support waveforms, non-MIDI instruments, and plugins that may add even more instruments, and piling that on top of an already confusing instrument instance system will just add more confusion.

**Comment by daveyarwood** [comment]
I'm not opposed to radically changing the instrument assignment/reference
syntax if someone has an idea that would be an improvement over what we
have now.

I've played around with a syntax that was more explicit about creating a
new instrument/group vs. using as existing one, but I found it difficult to
do this while also keeping the syntax simple and user-friendly. I think one
of the major selling points of Alda is its concise syntax. I like that an
Alda score can be as simple as "piano: c d e f g a b > c".

**Comment by daveyarwood** [comment]
I think the way it works currently is intuitive, we just need to explain it better in the documentation.

The first key thing that perhaps isn't clear enough in the docs is that assigning an alias is something you do when you _create_ an instance or group. After that, you always use the alias to refer to the instrument.

The second key thing is that you should not use a combination of named and unnamed things; if you name one thing, you should name all of them.

Does that make sense? I'd like to talk about this and figure out where exactly the confusion lies, and improve our documentation so that it doesn't confuse other people.

**Comment by elyisgreat** [comment]
not sure. there's still the problem of plugin instruments though...

**Comment by daveyarwood** [comment]
I'm not sure what you mean by "plugin instruments" -- can you elaborate on that?

**Comment by elyisgreat** [comment]
Alda will eventually have plugins, which may add more instruments. so for example:

```
piano "8bit": c d e f g
violin: c d e f g
8bit/violin "group": f e d c
```

If a plugin is added that adds a stock instrument `8bit`, there could be some problems...

**Comment by daveyarwood** [comment]
Oh, I see what you're saying. I don't think that will be problematic, though. Take the following score, for example:

```
piano "violin": c d e
violin: f g a
```

The first line creates a piano and names it "violin" -- now `violin` doesn't refer to the stock instrument violin anymore, it refers to that piano instance. In fact, it is now impossible to create a violin instance:

```
piano "violin": c d e
violin: f g a
violin "violin-2": b
violin-2: >c
```

In this score, a piano called "violin" is instantiated on the first line, and continued on the second line. On the third line, the same instrument is continued again and nicknamed "violin-2". On the fourth line, it is continued again. `piano`, `violin`, and `violin-2` all refer to the same piano instrument in this case, and there is no way to create a violin instance\*. Is this a problem? Only if you name your piano "violin"! 😛 

\*unless you use the stock instrument's full name `midi-violin` -- but let's not get into that!

The same logic will apply to any new instruments that get added. For example, if we add a `square-osc` instrument, and you have an old score where you have a `midi-square-lead` instance nicknamed `"square-osc"`, your score will still sound the same, using the `midi-square-lead` instrument, because that's the stock instrument you used when you instantiated it. The nickname doesn't play any role in determining what stock instrument is used.

**Comment by elyisgreat** [comment]
That doesn't make sense... In fact I would imagine that `violin "violin-2"` would call a new violin because its name is explicitly stated along with type.

**Comment by daveyarwood** [comment]
`violin "violin-2"` refers to the piano instance called `"violin"` in order to be consistent with the way new groups are instantiated from existing instances by referring to them by name. For example:

```
piano "violin": c d e
violin/guitar "piano-and-guitar": c
```

Here, on the first line, a piano is created and named "violin". On the second line, the same instance is reused along with a new guitar instance, to form the group named "piano-and-guitar."

So, if the `violin` in `violin/guitar` is the piano named `"violin"`, then shouldn't the `violin` in `violin "violin-2"` also refer to the piano named `"violin"`?

**Comment by elyisgreat** [comment]
No, as it seems to violate this part of the instances doc:

>A new instance of an instrument is created whenever a stock instrument is called with any nickname, either as part of a group or not.

Also, it seems confusing that two names can refer to the same instrument instance.

**Comment by jimcheetham** [comment]
Here's your problem:
> violin "violin-2" refers to the piano instance called "violin" in order
to be consistent with the way new groups are instantiated from existing
instances by referring to them by name.

You have the same problem with variable naming too - by insisting on an
implicit syntax, you're creating uncertainty. Things that are normally
thought to have been "reserved words" are being overwritten by the user.
You could introduce reserved words to prevent someone calling a piano
"violin", but you might not be able to track future plugin-generated
instruments.

Madness:
violin = a b c
violin "violin": violin

What would happen to instance names if you always required the "double
quotes" to refer to a user's reference?

piano "violin": c d e
violin: c d e
"violin": e d c

If you wanted the mix you suggested earlier, you'd do
piano "violin": c d e
"violin"/guitar "piano-and-guitar": c

If you also signalled user's variable names with a marker, you wouldn't
have to have rules like "has to be two characters at least, and not
starting with a number" :-)

$hook = a b >c<
piano: $hook b b

As a programmer, I'm used to seeing that sort of syntax.

-jim

**Comment by elyisgreat** [comment]
Ok; I think I have a pretty good compromise that should be pretty intuitive.

* Any call of the form `<type> <name>:` *must* create a *new instrument instance* of type `<type>` with name `<name>`. Duplicate names will always throw errors here.

* If a call is of the form `<type>:`, then the following happens:
    * If there exists an instrument with the name `<type>`, refer to that instrument. 
    * Else if it is the first call of a stock instrument, a new stock instrument instance of type `<type>` is created with a name to refer to it unambiguously. 
    * Else if it refers to a stock instrument, refer to the *most recently called* instrument of type `<type>`

* If a call is a group call, then it is treated exactly like multiple individual calls with no `<name>` argument (See: If a call is of the form `<type>:`). 

* However, if the group call has its own `<name>` argument, then it will reserve `<name>` to refer to that particular grouping. Duplicate names will always throw errors here.

**Comment by daveyarwood** [comment]
It seems like that's fairly close to what we have now, but with a couple of differences:

- After initializing a particular type of instrument with a name (like `trumpet "foo"`), the name of the stock instrument (`trumpet`) now refers to the most recently called instance of that type.

  (Currently, we don't have any defined behavior for which instrument the name of the stock instrument will select in this scenario. I think it just grabs the first instance it finds of that type.)

- Instrument instances in a _named_ group are not automatically new instances.

  (Currently, if you already have a named piano instance, and then you initialize a grouping called `piano/cello`, then both `piano` and `cello` will be new instances of those stock instruments; `piano` will not select the existing piano instance.)

---

Re: the first point, I do like the idea of defining a behavior for that scenario, but I'm not sure if "most recently used instance of that stock instrument" is the behavior we want. That would mean that, in a score where you have multiple named piano instances, if you choose to use `piano:` then the instance it selects will vary depending on which one was most recently called.

What if, instead of referring to the instance most recently called, the call would create (and then refer back to) a new instance? That would allow for one "anonymous" piano instance, alongside the named ones. For example:

```
piano "foo": c8 d e f g2
piano "bar": e8 f g a b2

# happens at the same time as foo and bar
piano: o3 c2 g
```

That behavior seems it might be easier for newcomers to understand, and could possibly be more useful. Although, I would still recommend NOT mixing and matching named vs. unnamed instances; if you find yourself naming one instance, you should name them all.

---

As for the second point, we would still have the problem of being forced to use an awkward syntax in order to create a named group of new instances:

```
piano "foo":
harpsichord "bar":
foo/bar "keyboards": c
```

Whereas currently you can just do:

```
piano/harpsichord: c
```

**Comment by daveyarwood** [comment]
I think the current system is intuitive as long as you don't mix and match named and unnamed things. What if we threw a descriptive error whenever you tried to do that? That way, newcomers to Alda would learn early how this works.

**Comment by elyisgreat** [comment]
Making mixing named and unnamed stock instruments of the same type illegal is probably the most intuitive and least ambiguous solution. One thing I would add is that I like the idea of calls of the form `<type> <name>:` should always create a new instance of `<type>` with name `<name>`, even if there is already an instrument with the name `<type>`. I also thing having a `.` syntax to refer to anonymous instruments in groups is necessary to make all instruments unambiguous.

**Comment by elyisgreat** [comment]
Here's the latest system more formalized:

Two important points:

1. Every name must have a one-to-one relationship with an instrument instance or group.
2. Every call is one of exactly four forms, which I am labelling here for convenience: 0–`<type> <name>:` 1–`<argument>:` 2–`<grouping>:` 3–`<grouping> <name>:`

* If the call is of form 0, it *must* create a *new instrument instance* of type `<type>` with name `<name>`. Duplicate names will always throw errors here.

* If a call is of form 1, then the following happens:
    * If there exists an instrument with the name `<argument>`, refer to that instrument. 
    * Else if there exists a stock instrument of type `<argument>` , and there is no named stock instrument instance of type `<argument>`, it refers to an unambiguous instrument instance of type `<argument>`
    * Else an ambiguity error is thrown

* If a call is of form 2, then it is treated exactly like multiple individual calls of form 1.

* If a call is of form 3, then it is treated exactly like multiple individual calls of form 1, with the following exceptions:
    * If one of the component calls refers to a stock instrument that is not one of the named instruments, it is possible to create a new instrument instance unambiguously, aliased to the new group using the reference `<groupname>.<instrument>`

**Comment by daveyarwood** [comment]
OK, great! So I think right now, we could make the following improvements:

- Add a `.` syntax for accessing a member of a group.
- When making a call of the form `<type> <name>` (and it's not a group), don't check for an instance named `type`; always create a new instance where `type` is expected to be a stock instrument.

  This will make it illegal to do, e.g.:

  ```
  piano "foo": c d e
  foo "bar": c d e
  ```

  This is currently allowed and it effectively "renames" foo to bar, but this is confusing and we shouldn't allow it. Instead, we should expect `foo` to be a stock instrument and throw an error because it isn't. (The moral of the story is: nicknaming a single instrument should always mean that you are creating a _new_ instance, not renaming an existing one.)

- Throw an error if you try to use a nickname that is the same as a stock instrument, e.g. `piano "violin":`
- Throw an error if you try to call an unnamed instrument instance after naming another instance\*.

\*Maybe we should only do this for instruments of the same type? For example, maybe this should be OK:

```
piano "foo": c8 d e f g
piano "bar": e8 f g a b
harmonica: c1
```

I think in this example, the purpose of the nicknames is to differentiate the two piano instances, and there is only one harmonica instance, so you shouldn't be required to come up with a nickname for it.

This, however, should not be OK:

```
piano "foo": c8 d e f g
piano: e8 f g a b
```

Since it would raise the question of whether `piano:` means the same piano or a new one.

Another thing we might not want to allow is mixing and matching unnamed and named instances within a group, regardless of whether we're using a nickname. For example, either of the following could throw an error:

```
piano "foo": c d e
foo/clarinet: f2.
```

```
piano "foo": c d e
foo/clarinet "baz": f2.
```

But these could be OK:

```
piano "foo": c d e
clarinet "bar":

foo/bar: f2.
```

```
piano "foo": c d e
clarinet "bar":

foo/bar "baz": f2.  
```

The idea being that if you're using a group (with or without a group name), you should either be A) creating new instances, or B) grouping together existing instruments, NOT some combination of the two.

**Comment by elyisgreat** [comment]
Sounds good. Don't forget to come up with a new formal rule set for describing these changes, and then update the docs with it. Only concern is this:

>Throw an error if you try to use a nickname that is the same as a stock instrument, e.g. piano "violin":

Plugin instruments would become a problem here. I think one way to solve this is by allowing a character in instrument names that is not allowed in stock instruments. This way, no matter what instruments get added, you can always make sure your names won't break. I also think this character should be allowed to come at the beginning of instrument names, however that is a separate debate.

**Comment by daveyarwood** [comment]
Oh yeah, we should make sure that isn't a problem. We should do our best to keep Alda scores forward-compatible, at least until the next major version release -- i.e. valid scores created during Alda 1.X.X should be playable at least until Alda 2.0.0. We definitely don't want to break people's scores every time we add new stock instruments!

I would prefer not to add extra required syntax at the beginning of instrument names.

What if we didn't throw an error when you try to name an instrument after a stock instrument, but we made the change I noted above (bullet point 2) where the form `<type> <name>` will always create a new instance of type `type`?

e.g.

```
piano "violin": c d e f  # legal
violin: g a b > c        # legal, still the same piano

violin "myViolin": c1~1  # creates a new instance of the violin stock instrument
```

That way, you could name your instances the names of stock instruments all you want, your references would work, and you wouldn't have to worry about inadvertently naming an instrument the name of a stock instrument that will be added in a future release.

**Comment by elyisgreat** [comment]
>What if we didn't throw an error when you try to name an instrument after a stock instrument, but we made the change I noted above (bullet point 2) where the form <type> <name> will always create a new instance of type type?

I like this, however you have to be careful about groups when doing this, especially if you want to distinguish between grouping existing instances and making new ones. 

```
piano "violin":
clarinet/violin "stuff": 

#is this creating two new instances, or grouping with the piano? Legality depends on this question. 
```

**Comment by daveyarwood** [comment]
Yeah, you're right. I think we could handle that by not allowing you to combine named and unnamed instances in a group.

In other words, if it's a group, we would check to see if...

- ...all of the group members are existing named instances -- if so, we use those instances.
- ...all of the group members are stock instruments -- if so, we handle them as if they are individual instruments.
- Otherwise, we throw an error because of the ambiguity.

**Comment by elyisgreat** [comment]
sounds good; what's the latest formal definition of the proposed rules?

**Comment by daveyarwood** [comment]
### `foo:`

- If `foo` refers to a previously named instrument or group, e.g. `piano-1:`...
  - ...refers to that instrument or group.

- If `foo` is a stock instrument, e.g. `piano:`...
  - ...and we don't have a `piano` yet in the score...
    - ...creates a new instance of the stock instrument`piano`.
    - ...subsequent calls to `piano` will reference that instrument.
  - ...and we already have a NAMED `piano` in the score...
    - ...throws an ambiguity error. (Any additional `piano`s must also be named.)
  - ...and we already have exactly one `piano`, and it doesn't have a name...
    - ...refers to that `piano`.

- Else, throws an "unrecognized instrument" error.

### `foo "bar":`

- `foo` is expected to be a stock instrument. If it's not, an error will be thrown.

- If `"bar"` was already used as the nickname of another instance, throws an error.

- Creates a new instance named `bar` of type `foo`, e.g.:
  - `piano "larry":` creates a new instance of the stock `piano` named `"larry"`
  - Subsequently in the score, `larry:` refers to that instance.

### `foo/bar:`

- If both `foo` and `bar` refer to previously named instrument instances...
  - ...refers to those instances.

- If both `foo` and `bar` are stock instruments, e.g. `piano/bassoon:`
  - ...follows the `foo:` rules above to select and/or create instances.
    - (new instances will be created for any instruments that don't exist yet in the score)

- If e.g. `foo` is a named instrument and `bar` is not, or vice versa (e.g. `foo/trumpet:`):
  - ...throws an ambiguity error. (Groups should be used for creating new instances or grouping existing ones, not both.)

### `foo/bar "baz":`

- If both `foo` and `bar` refer to previously named instrument instances...
  - ...refers to those instances.
  - ...creates an alias `"baz"` which can now be used to refer to those instances as a group.
  - ...subsequently, `baz.foo` and `baz.bar` are available to reference the group members, although you could also just keep calling them `foo` and `bar`.

- If both `foo` and `bar` are stock instruments, e.g. `piano/guitar "floop":`...
  - ...creates new instances for each group member.
  - ...creates an alias `"floop"` which can now be used to refer to those instances as a group.
  - ...subsequently, `floop.piano` and `floop.guitar` are available to reference the group members.

- If `foo` is a named instrument and `bar` is a stock instrument or vice versa, e.g. `foo/trumpet "quux":`...
  - ...throws an ambiguity error. (Groups should be used for creating new instances or grouping existing ones, not both.)

**Comment by elyisgreat** [comment]
Looks good! I would also definitely include this in the docs somewhere.

**Comment by daveyarwood** [comment]
TODO:

- [ ] Codify the rules above as test cases.
- [ ] For calls like `foo "bar":`, expect `foo` to be a stock instrument and throw an error if it's not.
- [ ] Throw an error for calls like `piano "foo":` if `"foo"` is already a previously used nickname in the score.
- [ ] Throw an error when mixing/matching named and unnamed instances of the same stock instrument in a score, e.g. `piano:` followed by `piano "foo":`, or vice versa.
- [ ] For groups (named or unnamed), throw an error unless the members are either all named instances or all stock instances.
- [ ] Add a `.` syntax for accessing members of a group.
- [ ] Include the rules in the docs. (Replace or update [this page](https://github.com/alda-lang/alda/blob/master/doc/instance-and-group-assignment.md)?)

**Comment by elyisgreat** [comment]
>Include the rules in the docs. (Replace or update [this page](https://github.com/alda-lang/alda/blob/master/doc/instance-and-group-assignment.md)?)

I think I would include the rules above somewhere in the documentation, and replace [this page](https://github.com/alda-lang/alda/blob/master/doc/instance-and-group-assignment.md) with a more user-friendly explanation of how the new rules work.

**Comment by elyisgreat** [comment]
Another thing to mention; I'm assuming nested group operators would work; if you had code of the form 

```
piano/guitar "foo":
clarinet "bob":
bob/foo.piano "bar":
bar.foo.piano: 
```

I would assume that `bar.foo.piano` would refer to the piano that is also in bar (though you may as well call it `foo.piano`).

**Comment by daveyarwood** [comment]
Nested group operators seems like an obscure use case, but I see no reason not to allow it.

Seems like `piano/piano "foo":` ought to create a new group consisting of two new piano instances, no?

**Comment by elyisgreat** [comment]
Yes, however consider this:

1. How do you distinguish between the pianos? does `foo.piano` refer to the first piano or the second piano?

2. What about if the duplicate reference is to a named instrument, like `foo/foo "bar":`?

I reckon the second case should be made illegal, as it doesn't make sense to have the same instrument in a group twice. However the case of `piano/piano` I think should be allowed. The only question is how to refer to the different instruments?

**Comment by daveyarwood** [comment]
Sure, I could see it being useful to define a group of the same instrument playing in unison, for example if you wanted to emulate a chorus effect.

I'm not sure how we should handle the `foo.piano` case if `foo` is two `pianos`... maybe we should throw an error there too? The moral of the story being that if you want to define a group consisting of two of the same instrument, and then access them individually, then you're better off giving the two instances names? e.g.

```
# not OK
piano/piano "foobar": c d e
foobar.piano: f

# OK
piano "foo":
piano "bar":
foo/bar "foobar": c d e
foo: f
```

Now we're back to the awkward syntax where you have to define and name instances without giving them any notes to play, but maybe this situation is rare enough that it's acceptable.

**Comment by elyisgreat** [comment]
Agreed. Probably could update the [ruleset](https://github.com/alda-lang/alda/issues/249#issuecomment-237040176) for group calling stating that group calls to the same stock instrument or named instrument are not allowed.

**Comment by daveyarwood** [comment]
Sounds good to me. Updated.

**Comment by elyisgreat** [comment]
I should also note that in the case of unnamed groups, it is still possible to encounter a case where only some instruments are being created anew:

```
piano: c d e f
piano/clarinet: g a b >c<
```

Should this throw an ambiguity error?

**Comment by daveyarwood** [comment]
No, that should re-use the same `piano` instance.

**Comment by elyisgreat** [comment]
rules look good then! I'm interested in how the progress is going on the implementation...

**Comment by daveyarwood** [comment]
I've been very busy lately, and this issue is not a priority. A PR would be much appreciated, otherwise I'll get to it when I can. I think it will be a while.

**Comment by elyisgreat** [comment]
>A PR would be much appreciated

How would that work?

**Comment by daveyarwood** [comment]
The logic for determining which instrument instances to use/create when calling a part is all in the [alda.lisp.score.part](https://github.com/alda-lang/alda/blob/master/server/src/alda/lisp/score/part.clj) namespace -- [`determine-current-instruments`](https://github.com/alda-lang/alda/blob/master/server/src/alda/lisp/score/part.clj#L58) is the most relevant part.

**Comment by daveyarwood** [comment]
If you're wanting general info about how to create a PR to a project on GitHub: https://help.github.com/articles/creating-a-pull-request/

**Comment by elyisgreat** [comment]
If I can figure out the clojure, I'll take a look.

**Comment by daveyarwood** [comment]
Awesome, sounds good! I realize it's a lot to ask of anybody to learn a new language just to contribute to an OSS project, and I feel bad that I don't have more time to tackle all of these Alda issues, but I'm basically working on Alda by myself, and there's only so much one person can do :)

**Comment by elyisgreat** [comment]
The clojure still goes over my head for me (although even if I knew the language it would probably be faster to write it yourself than me ask about all the contextual information). I could, if you'd like, write some java pseudocode to simulate calling instruments to a score. You might want to assign this to a contributor with some time who actually knows the language :P

**Comment by daveyarwood** [comment]
No worries! This shouldn't be hard for myself or another Clojure-savvy contributor to knock out -- the only obstacle for me is finding a pocket of free time :)

**Comment by elyisgreat** [comment]
Still interested in the pseudocode?

**Comment by daveyarwood** [comment]
Sure, that could be helpful -- I would just put it in a gist or pastebin or something so this issue doesn't get too noisy.

**Comment by elyisgreat** [comment]
The code started turning into a mess rather quickly, so I think I'm going to leave it up to you. sorry about that.

**Comment by daveyarwood** [comment]
Not a problem - we'll see what we can do!

**Comment by daveyarwood** [comment]
[1.0.0-rc46](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc46) is out, incorporating the changes described above.

I've updated [the docs](https://github.com/alda-lang/alda/blob/master/doc/scores-and-parts.md#how-instances-are-assigned) as well, summarizing the rules in what I hope is an intuitive way, with examples.

I'm pleased with the state of part and group assignment in Alda now, but I'm happy to discuss further if anyone has any questions or points of confusion going forward!
