### ISSUE TITLE
undefined variables bug

### ISSUE THREAD

**Issue by elyisgreat** [alda-lang/alda#251]
Was messing around with undefined variables in the REPL and found this bug:

```
> foo = 
16-Jul-24 11:31:48 ElysComSEdition.local.tld ERROR [alda.repl.core] - Invalid Alda syntax.

> foo = []
16-Jul-24 11:31:51 ElysComSEdition.local.tld ERROR [alda.repl.core] - Invalid Alda syntax.

> foo = foo

> foo
                                  ...                    
alda.lisp.events.variable/eval5080/fn  variable.clj:   18
                                  ...                    
alda.lisp.events.sequence/eval5057/fn  sequence.clj:   13
                  clojure.core/reduce      core.clj: 6544
                                  ...                    
```

(rest of repl log [here](http://pastebin.com/yhvwR6eV))

It seems as though you can set undefined variables equal to themselves (but not nothing or empty event blocks, which both throw syntax errors; in fact empty event blocks always throw syntax errors), and then when called it throws a StackOverflowException. However this seems to happen only the first time I do it.

A similar thing happens when I [set undefined variables to other undefined variables](http://pastebin.com/iWJUujH8).

I should mention that if you do in fact want to set a variable to nothing (as in empty score) you have to do `var = ()`, which makes sense, however `var = []` (and possibly `var = `) should also work.

**Comment by daveyarwood** [comment]
Alright, so it seems like there are 3 variable-related issues here:

1. Defining a variable using another, undefined variable appropriately throws an "undefined variable" error, but then if you do it again with a different variable, there is no error. There should be an error every time you try to use an undefined variable.

2. The parser does not allow an empty event sequence, `[]`. I see no reason why this shouldn't be supported.

3. It is possible to define a new variable as itself (e.g. `foo = foo`), resulting in a stack overflow when you try to use it.

I'm preparing a release that fixes all three issues.

**Comment by daveyarwood** [comment]
Fixed in [1.0.0-rc26](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc26).

**Comment by elyisgreat** [comment]
Seems like you can still define variables with undefined variables but the error throwing has been improved when they are used.

**Comment by daveyarwood** [comment]
I'll admit that that is a peculiarity with how Alda works, when compared to most (non-music) programming languages.

In a language like C, Python, Ruby, Clojure, etc., if you even try to define a variable that references an undefined variable, an error will be thrown:

```
ex.c:4:15: error: use of undeclared identifier 'bar'
  char* foo = bar;
              ^
```

```
>>> foo = bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'bar' is not defined
```

```
irb(main):001:0> foo = bar
NameError: undefined local variable or method `bar' for main:Object
	from (irb):1
	from /usr/local/var/rbenv/versions/2.0.0-p594/bin/irb:12:in `<main>'
```

```
boot.user=> (def foo bar)

clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: bar in this context, compiling:(/var/folders/h0/jb2j4f310zx08ynwfxw8lxg00000gn/T/boot.user4578767686728750423.clj:1:1)
             java.lang.RuntimeException: Unable to resolve symbol: bar in this context
```

These examples all fail in the same way -- when I say "hey, define this thing called `foo`, the value is `bar`), _the language runtime/compiler first tries to get the value of `bar` so that it can store it in memory and call it `foo`_. If anything on the right side of the `=` sign can't be evaluated because e.g. an error is thrown, then the whole variable-setting operation fails.

Alda, on the other hand, isn't set up like this. Instead of storing values, we're storing events. So when you write this in an Alda score:

```
foo = bar

piano: foo
```

The Alda parser interprets it as:

```
(alda.lisp/score
 (alda.lisp/set-variable :foo (alda.lisp/get-variable :bar))
 (alda.lisp/part {:names ["piano"]} (alda.lisp/get-variable :foo)))
```

So far, we haven't tried to play the score yet -- we're still in the parsing stage. The parser successfully read a `set-variable` event and a `get-variable` event. As far as the parser is concerned, `(get-variable :bar)` is a valid event even if `bar` hasn't been defined yet.

In the score evaluation stage, the `set-variable` event succeeds because as far as it's concerned, `(get-variable :bar)` is a valid event. It's not until we try to get `foo` that the score evaluation process will even try to retrieve the value of `bar`, so that's when the error gets thrown.

I agree that it would be better, e.g. for REPL usage, if the `set-variable` event failed if you tried to set the variable equal to a variable that hasn't been defined yet. It's just interesting because we can't compute the "value" of the event sequence ahead of time because we're working with events instead of values.

I think there may still be a way to do this (throw an error when trying to set the variable to something undefined, not when you try to get it back)... I'll take another look when I have a minute.

**Comment by daveyarwood** [comment]
OK, I figured it out! It ended up being pretty simple to make it work more like the languages I mentioned above.

As of [1.0.0-rc27](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc27), trying to use an undefined variable in the definition of another variable will fail immediately, e.g. `foo = bar` will result in an "undefined variable: bar" error.
