### ISSUE TITLE
midi output to non-java device

### ISSUE THREAD

**Issue by 0atman** [alda-lang/alda#259]
While there are some excellent soundfonts out there, and thanks to this project I am now aware of them, nothing can beat using your own DAW, VSTs or physical devices for output.

This feature would also give us MIDI file saving, in a round about way ("record" alda into any DAW, then save the midi to file from there)

**Comment by daveyarwood** [comment]
Great idea! I think this could potentially be a very easy feature to implement.

We are already firing MIDI note on/off events (as well as volume and panning messages and assigning instrument patches to channels) in real time, using our own scheduler. We're just sending these MIDI messages to a JVM MIDI synthesizer instance, instead of emitting them in a way that they could be used by another program.

We could add an option that would tell Alda to just emit the messages instead of sending them to the JVM MIDI synth.

**Comment by 0atman** [comment]
I'm none too familiar with the JVM or clojure, but where could I get started on this?

**Comment by daveyarwood** [comment]
That would be great! I'll be happy to help with any questions/problems you run into, including help with Clojure. I realize not a lot of people speak Clojure, but I want to do what I can to help change that :)

So here are my thoughts so far, and hopefully some of this is helpful:

I think the easiest way to start on this would be to just modify the code we have so that it's emitting the MIDI messages instead of playing them in the JVM, and get that setup working locally where Alda is emitting MIDI messages and your DAW is receiving them. (Then we can tweak it so that we still get the current behavior by default, but we can enable this new behavior via a CLI option -- we can worry about that part later.)

I don't know a whole lot about transmitting MIDI messages with Java yet, but from what I can tell, the first thing we need to figure out is how to choose the MIDI output device. I think the most flexible way would be to let the user tell us which device to use. We could make it so that the user runs `alda list-devices` or something and we show the available devices, then the user can run something like `alda --device 5 play -f my-score.alda`, and Alda would know to use MIDI device "5" (assuming they're numbered consistently?) to transmit MIDI messages instead of using its internal MIDI synth. (We can also worry about this part later -- to start, maybe you could just find the device you need and hard-code it in.)

---

Some resources about transmitting MIDI messages in Java:

* https://docs.oracle.com/javase/tutorial/sound/MIDI-messages.html
* https://docs.oracle.com/javase/7/docs/api/javax/sound/midi/MidiDevice.html
* https://docs.oracle.com/javase/7/docs/api/javax/sound/midi/Receiver.html
  * This confused me at first -- I expected the Transmitter interface to be the one with the `send` method, i.e. we create a transmitter instance and call `transmitter.send(msg)`. It turns out that with the Java Sound API, you get a reference to the receiver to which you want to send the message, and then you do `receiver.send(msg)`.
  * I think what we want to do is choose the correct MIDI device, obtain a reference to its Receiver, and send it messages.
* http://leapmidi.blogspot.com/2013/04/midi-between-java-application-and-daw.html
  * This guy is doing something very similar to what we want to do. The difference is that he wrote a little Java GUI app with a dropdown of all the MIDI devices available. Because Alda is a CLI app, instead of a dropdown, we can let the user choose the device via a command-line argument.
* http://www.java-forums.org/new-java/70056-help-java-real-time-midi.html
  * has example code working with receivers and transmitters

---

You can find details on building and running Alda locally in our [development guide](https://github.com/alda-lang/alda/blob/master/doc/development-guide.md), but the tl;dr version in this case is:

* Install [Boot](http://boot-clj.com).
* Clone the Alda repo.
* Run `boot dev -a server --alda-fingerprint` to run the server locally and see printed output.
  * You can make requests to the server normally with the Alda CLI client, e.g. `alda play -c 'piano: c d e'`.
  * You can make changes to the code and restart the server to pick up your local changes.
  * For example, try changing [the `play-score!` function](https://github.com/alda-lang/alda/blob/master/server/src/alda/now.clj#L89-L99) so that it just does `(println "testing alda dev setup")` and then run `alda play -c 'piano: c d e'`. Instead of hearing a piano, you should see `testing alda dev setup` printed in the server output.
  * Note: be sure you are not already running an Alda server first; if you are, run `alda stop` to free up the port.

**Comment by 0atman** [comment]
All right! That seems very comprehensive, thank you! I'm on #alda on slack now, so I'll shoot you some questions if I get stuck if I may?

**Comment by daveyarwood** [comment]
Sounds good!

**Comment by 0atman** [comment]
started work on this now, PREPARE YOURSELF FOR A PR

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-sound-engine-clj/issues/7.
