### ISSUE TITLE
Explain the ZMQ usage in more detail please

### ISSUE THREAD

**Issue by jimcheetham** [alda-lang/alda#265]
I'm thinking of talking to the alda server from (multiple, asynchronous) processes that aren't the existing alda client :-)

As such I need to hold a ZMQ conversation, and I'm not quite following what I'm seeing on the wire at the moment. You described your setup as "REQ/RES", but I don't see this pattern in the ZMQ guide. Did you mean "REQ/REP"?

JeroMQ seems to be using ZMTP/2.0 (strictly, 15/ZMTP) but I was confused reading the packet trace, where the client claims to be a DEALER and the server possibly claims to be a ROUTER (or possibly just sends an invalid framing packet!). So some clarification would be appreciated.

The example I took :- 
$ sudo tcpdump -w /tmp/a -i lo port 27713 &
$ alda play -c "piano: a b"
[27713] Playing...
$ kill %1
...

 ```
   00000000  ff 00 00 00 00 00 00 00  01 7f                     ........ ..
00000000  ff 00 00 00 00 00 00 00  01 7f 01 05               ........ ....
    0000000A  01 06                                              ..
    0000000C  00 00                                              ..
0000000C  00 00 01 33 7b 22 63 6f  6d 6d 61 6e 64 22 3a 22   ...3{"co mmand":"
0000001C  70 6c 61 79 22 2c 22 62  6f 64 79 22 3a 22 70 69   play","b ody":"pi
0000002C  61 6e 6f 3a 20 61 20 62  22 2c 22 6f 70 74 69 6f   ano: a b ","optio
0000003C  6e 73 22 3a 7b 7d 7d 00  04 70 6c 61 79            ns":{}}. .play
    0000000E  01 00 00 24 7b 22 73 75  63 63 65 73 73 22 3a 74   ...${"su ccess":t
    0000001E  72 75 65 2c 22 62 6f 64  79 22 3a 22 50 6c 61 79   rue,"bod y":"Play
    0000002E  69 6e 67 2e 2e 2e 22 7d                            ing..."} 
```

This looks like a server-announced ZMTP interoperability header, followed by the client claiming to be a DEALER. I don't understand the "01 06" issued at 000A in response to that.

Also, it looks like we send a JSON {"command":...} followed by just the word "play" in a second frame; where can I find the explanation of that command sequence?

**Comment by daveyarwood** [comment]
You make a good point -- to make this project more developer-friendly, I can certainly document how we're using ZMQ. I will likely add a page in the docs, sort of an extension of the [development guide](https://github.com/alda-lang/alda/blob/master/doc/development-guide.md) but dealing specifically with our use of ZMQ.

One issue is that I documented [here](https://github.com/alda-lang/alda/blob/master/doc/development-guide.md#aldaserver) that requests can be made "via any client that can make TCP/IP requests to a ZeroMQ REQ/RE[P] socket." This was originally true when I took my first stab at using ZMQ instead of an HTTP server -- at that point, the server was binding a REP socket and the client was making requests via a REQ socket.

But then I changed it and neglected to update the docs. What we have now is an implementation of the [Paranoid Pirate Pattern](http://zguide.zeromq.org/page:all#Robust-Reliable-Queuing-Paranoid-Pirate-Pattern), with a server routing requests between clients and workers. One notable difference is that the client doesn't use a REQ socket anymore, but a DEALER socket, as you noticed. As I was fiddling with Alda's ZMQ architecture, I learned that ROUTER and DEALER sockets are less rigid about the message formats, which ended up being useful.

I'll document this properly in the Alda developer docs, but a client->server message has three frames:

1) the return address frame of the client
2) a JSON string representing the client's request
3) just the command from the request, as a string

Frame 3 is used only by the server to determine whether the request is something the server itself should handle, or if the message should be forwarded to a worker.

There are also 1-frame heartbeat messages sent back and forth between the server and workers, but this should be transparent if you're only building an alternate client.

BTW, as someone with more of a background in ZMQ than I, your input on how we have things set up would be super helpful! It's possible that there are things I'm not doing quite right, or ways we could improve the current setup.

**Comment by daveyarwood** [comment]
@jimcheetham I sat down and documented as much as I could about the way we're using ZeroMQ in Alda: [ZeroMQ Architecture](https://github.com/alda-lang/alda/blob/master/doc/zeromq-architecture.md)

One thing I'd really like to do is to make it easy for other developers to try their hand at writing their own Alda clients/servers/workers, so the document above is basically a spec outlining the requirements for each role / describing what it needs to do. This is based on what each role currently does, so I expect this document to change over time... I'll try to be diligent about keeping it up to date with the current state of Alda's components.

One thing I didn't do was create an exhaustive list of all of the available commands that a server/worker can understand and their various options. That could be added, though, if it would be useful. I imagine it might :)

**Comment by jimcheetham** [comment]
Excellent Dave, thanks very much. I think you need to add an explicit
version comment in that document, to say that you're using JeroMQ version
whatever, that supports ZMTP whatever - IIRC the current JeroMQ uses ZMTP
spec:15 but you should check that.

The multiple workers - can they output sound simultaneously?

**Comment by daveyarwood** [comment]
Good idea -- I'll look into that.

The workers can output sound simultaneously -- each one is running as a separate process with its own JVM and its own audio environment (MIDI synth instance, etc.)  So the number of scores you can play at the same time is limited to the number of workers you have running. For example, with the default setting of 2 workers:

```
$ alda play -f examples/hello_world.alda
[27713] Playing...

$ alda play -f examples/hello_world.alda
[27713] Playing...

$ alda play -f examples/hello_world.alda
[27713] ERROR All worker processes are currently busy. Please wait until playback is complete and try again.
```

The workers send `BUSY` heartbeats while they are playing, so the server knows to "keep them alive" (i.e. continue to send them heartbeats), but not to consider them available for playing scores until they start sending `AVAILABLE` heartbeats again.

**Comment by daveyarwood** [comment]
I've added version info to the ZeroMQ architecture doc. I did the Clojure equivalent of [this](https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/version.java) to have the Alda server report its libzmq version, and it is libzmq 3.2.5. According to the JeroMQ README, it uses ZMTP/2.0.

**Comment by daveyarwood** [comment]
@jimcheetham Just a heads up that I made a couple of minor adjustments to our ZMQ message structure in [1.0.0-rc42](https://github.com/alda-lang/alda/releases/tag/1.0.0-rc42). Details can be found in the release notes / ZeroMQ architecture doc.

**Comment by jimcheetham** [comment]
I'm looking forward to getting a chance to play with it :-)

**Comment by daveyarwood** [comment]
I've added [a comprehensive list of example messages](https://github.com/alda-lang/alda/blob/master/doc/zeromq-messages.md) to the documentation.

I think things are pretty well-documented at this point, but if you have any other questions, don't hesitate to ask!

**Comment by jimcheetham** [comment]
Thanks for that extra work. It does indeed trigger an extra question ...

Why "parse"? Or perhaps, given that we have "play" that does "parse + emit
sound", is there a way to provide the map representation and get the server
to emit sound *faster* than having to do its own parsing at the time?

Am I right in comparing the Alda code that is the normal input to "source
code", and the map representation to "object code", with the server as the
run-time that emits the output sound?

If that's so, my thinking at the moment is towards generating object code
from a different source language ... :-)

-jim

**Comment by daveyarwood** [comment]
> Am I right in comparing the Alda code that is the normal input to "source
code", and the map representation to "object code", with the server as the
run-time that emits the output sound?

I think that's a great comparison. When Alda source code is parsed, the result emitted by the parser is something that looks like this (using a Clojure REPL here to demonstrate the `parse-input` function):

```clojure
alda.parser=> (require 'alda.lisp)
nil
alda.parser=> (parse-input "piano: c8 d e f g")
(alda.lisp/score (alda.lisp/part {:names ["piano"]} (alda.lisp/note (alda.lisp/pitch :c) (alda.lisp/duration (alda.lisp/note-length 8))) (alda.lisp/note (alda.lisp/pitch :d)) (alda.lisp/note (alda.lisp/pitch :e)) (alda.lisp/note (alda.lisp/pitch :f)) (alda.lisp/note (alda.lisp/pitch :g))))
alda.parser=> (eval *1)
{:chord-mode false, :current-instruments #{"piano-heRYJ"}, :events #{#alda.lisp.model.records.Note{:offset 750.0, :instrument "piano-heRYJ", :volume 1.0, :track-volume 0.7874015748031497, :panning 0.5, :midi-note 65, :pitch 349.2282314330039, :duration 225.0, :voice nil} #alda.lisp.model.records.Note{:offset 250.0, :instrument "piano-heRYJ", :volume 1.0, :track-volume 0.7874015748031497, :panning 0.5, :midi-note 62, :pitch 293.6647679174076, :duration 225.0, :voice nil} #alda.lisp.model.records.Note{:offset 1000.0, :instrument "piano-heRYJ", :volume 1.0, :track-volume 0.7874015748031497, :panning 0.5, :midi-note 67, :pitch 391.99543598174927, :duration 225.0, :voice nil} #alda.lisp.model.records.Note{:offset 500.0, :instrument "piano-heRYJ", :volume 1.0, :track-volume 0.7874015748031497, :panning 0.5, :midi-note 64, :pitch 329.6275569128699, :duration 225.0, :voice nil} #alda.lisp.model.records.Note{:offset 0, :instrument "piano-heRYJ", :volume 1.0, :track-volume 0.7874015748031497, :panning 0.5, :midi-note 60, :pitch 261.6255653005986, :duration 225.0, :voice nil}}, :beats-tally nil, :instruments {"piano-heRYJ" {:octave 4, :current-offset #alda.lisp.model.records.AbsoluteOffset{:offset 1250.0}, :key-signature {}, :config {:type :midi, :patch 1}, :duration 0.5, :min-duration nil, :volume 1.0, :last-offset #alda.lisp.model.records.AbsoluteOffset{:offset 1000.0}, :id "piano-heRYJ", :quantization 0.9, :duration-inside-cram nil, :tempo 120, :panning 0.5, :current-marker :start, :time-scaling 1, :stock "midi-acoustic-grand-piano", :track-volume 0.7874015748031497}}, :markers {:start 0}, :cram-level 0, :global-attributes {}, :nicknames {}, :beats-tally-default nil}
; pretty-print the above
alda.parser=> (pp)
{:chord-mode false,
 :current-instruments #{"piano-heRYJ"},
 :events
 #{{:offset 750.0,
    :instrument "piano-heRYJ",
    :volume 1.0,
    :track-volume 0.7874015748031497,
    :panning 0.5,
    :midi-note 65,
    :pitch 349.2282314330039,
    :duration 225.0,
    :voice nil}
   {:offset 250.0,
    :instrument "piano-heRYJ",
    :volume 1.0,
    :track-volume 0.7874015748031497,
    :panning 0.5,
    :midi-note 62,
    :pitch 293.6647679174076,
    :duration 225.0,
    :voice nil}
   {:offset 1000.0,
    :instrument "piano-heRYJ",
    :volume 1.0,
    :track-volume 0.7874015748031497,
    :panning 0.5,
    :midi-note 67,
    :pitch 391.99543598174927,
    :duration 225.0,
    :voice nil}
   {:offset 500.0,
    :instrument "piano-heRYJ",
    :volume 1.0,
    :track-volume 0.7874015748031497,
    :panning 0.5,
    :midi-note 64,
    :pitch 329.6275569128699,
    :duration 225.0,
    :voice nil}
   {:offset 0,
    :instrument "piano-heRYJ",
    :volume 1.0,
    :track-volume 0.7874015748031497,
    :panning 0.5,
    :midi-note 60,
    :pitch 261.6255653005986,
    :duration 225.0,
    :voice nil}},
 :beats-tally nil,
 :instruments
 {"piano-heRYJ"
  {:octave 4,
   :current-offset {:offset 1250.0},
   :key-signature {},
   :config {:type :midi, :patch 1},
   :duration 0.5,
   :min-duration nil,
   :volume 1.0,
   :last-offset {:offset 1000.0},
   :id "piano-heRYJ",
   :quantization 0.9,
   :duration-inside-cram nil,
   :tempo 120,
   :panning 0.5,
   :current-marker :start,
   :time-scaling 1,
   :stock "midi-acoustic-grand-piano",
   :track-volume 0.7874015748031497}},
 :markers {:start 0},
 :cram-level 0,
 :global-attributes {},
 :nicknames {},
 :beats-tally-default nil}
nil
```

You could think of this parsed "score map" as a sort of object code. This is the data that the sound engine component of Alda actually uses when it performs the score.

Generating this object code from a different source language is an interesting idea. One thing we would need to add in Alda is an option to play a score that has already been parsed. Then you could do something like:

```
$ alda parse -m -f my-score.alda > my-score.ao
$ alda play --object -f my-score.ao
```

Another thing worth noting is that the `alda parse` `-m`/`--map` option generates a string of JSON, not EDN which is the Clojure data structure the sound engine actually uses:

```bash
$ alda parse -m -f examples/hello_world.alda
{"chord-mode":false,"current-instruments":["piano-mGSRb"],"events":[{"offset":2000.0,"instrument":"piano-mGSRb","volume":1.0,"track-volume":0.7874015748031497,"panning":0.5,"midi-note":60,"pitch":261.6255653005986,"duration":1350.0,"voice":null},{"offset":1500.0,"instrument":"piano-mGSRb","volume":1.0,"track-volume":0.7874015748031497,"panning":0.5,"midi-note":64,"pitch":329.6275569128699,"duration":225.0,"voice":null},{"offset":250.0,"instrument":"piano-mGSRb","volume":1.0,"track-volume":0.7874015748031497,"panning":0.5,"midi-note":62,"pitch":293.6647679174076,"duration":225.0,"voice":null},{"offset":0,"instrument":"piano-mGSRb","volume":1.0,"track-volume":0.7874015748031497,"panning":0.5,"midi-note":60,"pitch":261.6255653005986,"duration":225.0,"voice":null},{"offset":1250.0,"instrument":"piano-mGSRb","volume":1.0,"track-volume":0.7874015748031497,"panning":0.5,"midi-note":65,"pitch":349.2282314330039,"duration":225.0,"voice":null},{"offset":1000.0,"instrument":"piano-mGSRb","volume":1.0,"track-volume":0.7874015748031497,"panning":0.5,"midi-note":67,"pitch":391.99543598174927,"duration":225.0,"voice":null},{"offset":750.0,"instrument":"piano-mGSRb","volume":1.0,"track-volume":0.7874015748031497,"panning":0.5,"midi-note":65,"pitch":349.2282314330039,"duration":225.0,"voice":null},{"offset":1750.0,"instrument":"piano-mGSRb","volume":1.0,"track-volume":0.7874015748031497,"panning":0.5,"midi-note":62,"pitch":293.6647679174076,"duration":225.0,"voice":null},{"offset":500.0,"instrument":"piano-mGSRb","volume":1.0,"track-volume":0.7874015748031497,"panning":0.5,"midi-note":64,"pitch":329.6275569128699,"duration":225.0,"voice":null}],"beats-tally":null,"instruments":{"piano-mGSRb":{"octave":4,"current-offset":{"offset":3500.0},"key-signature":{},"config":{"type":"midi","patch":1},"duration":3.0,"min-duration":null,"volume":1.0,"last-offset":{"offset":2000.0},"id":"piano-mGSRb","quantization":0.9,"duration-inside-cram":null,"tempo":120,"panning":0.5,"current-marker":"start","time-scaling":1,"stock":"midi-acoustic-grand-piano","track-volume":0.7874015748031497}},"markers":{"start":0},"cram-level":0,"global-attributes":{},"nicknames":{},"beats-tally-default":null}
```

The intent of this change was to make it convenient to pipe the result to a CLI tool like [`jq`](https://stedolan.github.io/jq/) and get specific information out of the score, for example a list of just the offsets of every note in the score:

```bash
$ alda parse -m -f examples/hello_world.alda | jq '.events[] .offset'
1250
1750
1500
1000
500
2000
250
750
0
```

We could easily add an option to emit EDN instead of JSON though, for convenience in working with the EDN as "object code." Or perhaps EDN should be the default, and we could add an option to emit JSON like we're doing now.
