### ISSUE TITLE
Cannot start alda using portable JRE

### ISSUE THREAD

**Issue by nkonk** [alda-lang/alda#282]
I got a portable version of OpenJDK8 from https://github.com/ojdkbuild/ojdkbuild/tree/master/src/java-1.8.0-openjdk to run Alda on windows server 2012

After setting JAVA_HOME and PATH variables properly (i can run the java --version command and it does show the right version)

When i execute alda.exe it says this app needs java 1.7 and takes to the download website.

Am i missing any step ? 
Or does the build.boot need to be changed to accomodate OpenJDK8?

Thanks in advance :)
This is an awesome project

**Comment by daveyarwood** [comment]
Hi!

Hmm... Alda should only require Java 1.7+ to run, so it seems unusual that you would get an error message if you're using JDK8. I suspect that there is some issue with your Java installation.

I'm afraid this is a bit difficult for me to troubleshoot because I don't know all the details of how Java installations work on Windows.

Does it work if you download and install the latest Oracle JRE from [this page](http://www.oracle.com/technetwork/java/javase/downloads/index.html)?

**Comment by feldoh** [comment]
I think you'll need JDK7_BOOTCLASSPATH set too if you're building it. Also later versions of Java don't rely on JAVA_HOME anymore which is why it's not set automatically you need to actually print the variable from the command line to prove it's available to that cli. Also if I recall correctly, you may need to restart for it to pickup the path changes in server 2012.

**Comment by nkonk** [comment]
@daveyarwood Hmm.. I was thinking the same too.. But i would really love to get it up on this portable one.Thanks 

@feldoh Yep.. I saw that in the build.boot but i was just trying to run the pre-compiled binary..
Well, i set the path manually(of JRE_HOME and JAVA_HOME) and reloaded all the powershell's.I felt a restart wasnt necessary to get path changes. But i'll try that too and let you guys know.

**Comment by nkonk** [comment]
Using a standard Java installation works.
But a portable installation doesn't seem to work so well. 
Maybe after some time I'll try again to get it up and running on it.
Might not be an issue with alda per se.Closing issue.
Thank you guys.
