### ISSUE TITLE
How to add a new instrument?

### ISSUE THREAD

**Issue by abhi18av** [alda-lang/alda#287]
Hey, I'm trying out Alda and loving it!

I wonder if there's a way to add the Chinese Flute [Dizi](https://www.youtube.com/watch?v=YZJ5use6wVk). If yes, how to do it - could you please guide me?

**Comment by daveyarwood** [comment]
Hey, glad to hear you're enjoying it!

We are currently limited to [instruments available in the General MIDI spec](http://soundprogramming.net/file-formats/general-midi-instrument-list/), so there is not an easy way to add new instruments, unfortunately.

Eventually, I would like to add the ability to create your own custom instruments based on samples (e.g. a wav file), but I think it will be a while before we have that feature.

If you want to get the sound of a dizi in your score now, I have a couple of ideas:

- You can use a similar-sounding General MIDI instrument like a flute, pan-flute, or shakuhachi.
- You can install a custom soundfont that has a dizi. I found a [Chinese Winds soundfont](https://www.soundfontdownloads.com/products/chinese-winds) at soundfontdownloads.com that actually includes [many different sampled dizi instruments](https://www.soundfontdownloads.com/sites/default/files/World%20Chinese%20Winds%20SoundFont.pdf). The soundfont is not free, but I thought I'd mention it as a way to get a realistic-sounding dizi in your Alda scores.

**Comment by abhi18av** [comment]
Wow, I love the enthusiasm @daveyarwood !!

And thanks a lot for such a detailed answer, I've found this to be really helpful :fireworks: 

Hey, as an aside could you tell me why did you choose the Java backend, as opposed to the CLR or NodeJS backend, is something in the pipeline?

**Comment by daveyarwood** [comment]
The real reason is that the Java backend is the most mature version of Clojure, especially in 2012 when I started working on Alda.

But I think another major benefit of the JVM backend is that it's easier to build an executable that anybody can run without having to install any dependencies. The only requirement is that your computer have a reasonably up-to-date version of Java, which most people with new-ish computers already have. I think it's really important for Alda to approachable for people with little programming/development experience.

Another good thing about the JVM is that it comes with its own built-in MIDI synthesizer that is practically guaranteed to work out-of-the-box.

The Java/Clojure ecosystem also has a ton of useful libraries, which meant less code that I had to write to get Alda up and running. For example, I didn't have to write my own parser library or scheduling system.

The Node.js ecosystem is also rich, and I have thought about an alternative version of Alda that uses a Node.js backend instead. One advantage there would be faster start-up time, and perhaps a more stable version of ZeroMQ. It is apparently possible to use the [Web Audio API on Node.js](https://github.com/sebpiq/node-web-audio-api), which, along with [MIDI.js](https://github.com/mudcube/MIDI.js/), could give us all we need to reproduce the Alda sound engine.

The work I'm doing on #186 right now will help get us to a place where we can experiment with swapping out small pieces of Alda with alternative implementations in other languages. I am very curious to experiment with porting Alda to ClojureScript (which compiles to JavaScript) so it could be embedded into a website.

**Comment by abhi18av** [comment]
@daveyarwood  I've added Alda to the list of [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners). Hope you don't mind :smile: 

[Alda](https://github.com/MunGell/awesome-for-beginners/pull/47/commits/f29965fb8e52a0e5dfef9c1031a602d067156a87) with a beginner-friendly [low-hanging-fruit tag]  (https://github.com/MunGell/awesome-for-beginners/pull/47/commits/f29965fb8e52a0e5dfef9c1031a602d067156a87)

**Comment by daveyarwood** [comment]
I don't mind, thanks for doing that! :beers:
