### ISSUE TITLE
Alda in not printing

### ISSUE THREAD

**Issue by dgrmunch** [alda-lang/alda#294]
This is the Alda code of my file **song1.alda**:

```
 (println "Start")
 piano:
   (schedule #(println "playing c")) c8
   (schedule #(println "playing d")) d
   (schedule #(println "playing e")) e
   (schedule #(println "playing f")) f
   (schedule #(println "playing g")) g2
```

If I write in my terminal `alda play -f song1.alda` the notes are played but the output result in the terminal is:
```
[27713] Parsing/evaluating...
[27713] Playing...
```

**Comment by elyisgreat** [comment]
iirc printout was removed awhile back. Also don't forget to read #293 before submitting an issue :)

**Comment by daveyarwood** [comment]
I've captured this issue here: https://github.com/alda-lang/alda-server-clj/issues/1

There is a detailed explanation in that issue, but the tl;dr is that Alda used to run as a single process, so printing the output was as simple as, well, printing the output. But then, the setup changed so that there is a client that the user interacts with, as well as a server and worker processes running in the background. The worker processes are the ones that evaluate your score, and they're running in the background, so we'll have to jump through some hoops to get the worker to send their output to the client and have the client print it.
