### ISSUE TITLE
Octaves and Notes

### ISSUE THREAD

**Issue by MinaBombo** [alda-lang/alda#298]
Isn't it a bit misleading that C3 doesn't mean C note the thirds octave and instead means C duration 3? xD

**Comment by elyisgreat** [comment]
imo it's a lot faster when writing to have c4 mean a quarter note c instead of the pitch "C4", since typically I write within the range of a few octaves, whereas the duration might change a lot.

Also, it seems like you have a lot of questions, which is great, except you also haven't read #293 yet. Also, feel free to chat [on slack](http://slack.alda.io/)!

**Comment by MinaBombo** [comment]
I totally agree but nevertheless musicians who are accustomed to numbers relating to octaves might get misguided 
And think about arranging harmonies for different voice types with different octaves
I suggest adding a way of accessing a note in a certain octave directly 
And sorry I forgot to change the title

**Comment by elyisgreat** [comment]
>I suggest adding a way of accessing a note in a certain octave directly

try `o$n $p`, where $n is the octave you want and $p is the note you want. For example, `o4 g` will always play a "G4" (about 392 Hz).

**Comment by MinaBombo** [comment]
My bad, overlooked that notation.
