### ISSUE TITLE
help with installation..

### ISSUE THREAD

**Issue by touxstone** [alda-lang/alda#304]
Hi, 
Interested in this project I got some issues, however. I do not know what I'm missing. I'm going on `fedora27` got installed `boot` & followed installation instructions apparently OK.
 `$ alda update` reports OK, updated. Ran the sound-fonts script also without errors, though, when checking at `~/.gervill` dir it still shows as only file: `soundbank-emg.sf2`. Then, when running `$ alda repl` I got the following output and it never ends. 
Is it there something I'd overlooked?.
```bash
[27713] Starting Alda server...
[27713] Server up ✓
[27713] Starting worker processes...
```
So, something is not going OK, but I'm still unable to release what. I'd appreciate any help..

**Comment by daveyarwood** [comment]
Hello!

Let's start with `soundbank-emg.sf2` -- if that's the only file you're seeing, then that's not necessarily a problem, because the script replaces the default one.

You can tell if that part worked by checking the size of that file. If it's about 142 MB, then the script worked:

```bash
$ du -sch ~/.gervill/*
142M    /home/dave/.gervill/soundbank-emg.sf2
142M    total
```

Re: worker processes, they do take quite a while to start. Is it taking longer than 60 seconds?

**Comment by touxstone** [comment]
Hi, @daveyarwood thanks for that tip. Yh, the file (`~/.gervill/soundbank-emg.sf2`) size is 142 MB as you've posted. So, that's done isn't?. 
& The worker processes never end..

**Comment by daveyarwood** [comment]
Do you see any error logs in `~/.alda/error.log`?

**Comment by touxstone** [comment]
Hey, yep.
```bash
[alda.worker:327] - Unable to reach the server.
...
...
```

**Comment by daveyarwood** [comment]
Hmm, so this will take a bit of guesswork, but maybe we can figure it out.

Can you try running the server in the foreground and paste the output here? Here's what I see on my machine:

```bash
$ alda -v -p 27714 server
18-03-30 21:28:32 moondog INFO [alda.server:243] - Binding frontend socket on port 27714...
18-03-30 21:28:32 moondog INFO [alda.server:256] - Binding backend socket on port 35345...
18-03-30 21:28:32 moondog INFO [alda.server:270] - Spawning 2 workers...
18-03-30 21:29:33 moondog DEBUG [alda.server:203] - Supervisor approves of the current number of workers.
```

Note that 1 minute elapsed in between the last 2 messages -- there is no logging that shows when workers connect, only a log every 60 seconds showing whether there are enough workers (i.e. 2).

**Comment by touxstone** [comment]
So my output looks like following...
```bash
alda -v -p 27714 server
18-03-31 12:29:15 btxarly INFO [alda.server:243] - Binding frontend socket on port 27714...
18-03-31 12:29:15 btxarly INFO [alda.server:256] - Binding backend socket on port 38659...
18-03-31 12:29:15 btxarly INFO [alda.server:270] - Spawning 2 workers...
18-03-31 12:30:15 btxarly INFO [alda.server:190] - Supervisor says we need more workers.
18-03-31 12:30:15 btxarly INFO [alda.server:191] - Starting 2 more worker(s)...
18-03-31 12:31:15 btxarly INFO [alda.server:190] - Supervisor says we need more workers.
18-03-31 12:31:15 btxarly INFO [alda.server:191] - Starting 2 more worker(s)...
18-03-31 12:32:15 btxarly INFO [alda.server:190] - Supervisor says we need more workers.
... (repeat)
```

**Comment by daveyarwood** [comment]
OK, thanks for staying with me so far. On the surface, the issue seems to be that the workers the server is starting aren't connecting to the server.

Admittedly, I think we need a better way to diagnose issues like these. I've filed [an issue](https://github.com/alda-lang/alda-client-java/issues/33) to add an `alda doctor` command that will help us diagnose what's going on when users experience issues like this one.

If you'd like, we can continue to try and troubleshoot your particular issue, although it will involve more manual digging like we've been doing so far. I'm happy to do that, if you don't mind trying a few more things. We should move this to a separate issue though, as [issues are not to be filed here](#293). I recommend opening an issue in https://github.com/alda-lang/alda-server-clj, where it will be more relevant.
