### ISSUE TITLE
Add Alda to the AUR

### ISSUE THREAD

**Issue by qwetboy10** [alda-lang/alda#308]

**Comment by daveyarwood** [comment]
I'm going to close this issue for now -- we're trying to keep this repo free of issues, and file issues instead in the other repos in the alda-lang org -- see #293.

In this case, it isn't clear to me which repo would be the best fit for this issue, but maybe this is something best discussed on [Slack](https://slack.alda.io) instead of GitHub issues.

**Comment by 0x715C** [comment]
I've submitted a package '[alda-bin](https://aur.archlinux.org/packages/alda-bin/)'. This simply puts the pre-compiled binary in /usr/bin/ .
I've been trying to make an 'alda-git' package, but I get the message "Merge conflict: not adding alda" during build, which brings up another program. Generated binary works fine though.

**Comment by daveyarwood** [comment]
Great!

I can confirm that the `Merge conflict: not adding alda` message is scary-sounding, but benign. I see it every time I build the `alda` executables that I release on GitHub.
