### ISSUE TITLE
Stack-based attributes

### ISSUE THREAD

**Issue by bluebear94** [alda-lang/alda#46]
Perhaps `a_` and `a^`?

**Comment by daveyarwood** [comment]
I'm not sure if I'm fully understanding this issue, but currently, you can play a note in different octaves using `<` and `>`, i.e.

    a > a > a < a < a

**Comment by crisptrutski** [comment]
Sounds like a request to pop back to the previous octave after that note - a bit like `ctr-O` in vim

**Comment by crisptrutski** [comment]
@daveyarwood had another brain fart around this:

It could be cool to have a generic stack of of contexts (tempo, key, octave, etc) that can be pushed and popped (say for the switch between the major then minor then back, common with Spanish guitar). 

Thinking something where the stack stores just changes, so values not actually set would not be changed on pop OR push (so not just captured at `push` time)

With something like this in place, could introduce a shorthand for just-one-note changed (maybe when `~` appears as a prefix`

To give examples:

```
a b > c < b a # before
a b ~> c b a # after
```

NOTE: This primitive could even be used to implement those *cram* expressions (push/pop a tempo change)

**Comment by daveyarwood** [comment]
@crisptrutski Good idea! The stack concept would be especially useful if we can come up with a syntax to specify how long the effect would be pushed onto the stack before being popped off again. Curly braces and square brackets are already reserved for upcoming features (cram expressions and variables, respectively), but theoretically, if we *could* use curly braces, we could maybe do something like this...

    # before
    (volume 80) o3 c d e f g a b (volume 100) > c
    # after
    ~(volume 80) ~o3 { c d e f g a b }  c

Since this would be implemented as a stack under the hood, we could easily support nesting these "scoped attributes." Basically, a (metaphorical) "open curly brace" would mean "push these attributes onto the stack," and "close curly brace" would mean "pop one level of scoped attributes off the stack"

(we would just need to come up with some alternative to curly braces)

**Comment by crisptrutski** [comment]
Perhaps a here-string like syntax, which would let each stack use a custom character, eg. `o3 %(a b o5 %{c d})`, which could also help differentiate between closing marks if the user wanted.

One thing to watch out for is that I think the grammer should be able to cope with hanging stacks, ie. they should close in the right order if differentiated, but don't all need to be closed. I think this could be useful once variables and abstraction come into play, for example to separate the start and end of movement into separate fragments.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-core/issues/4.
