### ISSUE TITLE
Make octave-change direction user-configurable

### ISSUE THREAD

**Issue by sansumbrella** [alda-lang/alda#60]
This may be a duplicate of #59.

I just read through the gentle introduction; great stuff! However, I feel like the octave change notation is backwards and would love to be able to configure it in my own programs.

Both graphically and mathematically, `a > b` suggests a downward change from `a` to `b`. I imagine it would read more naturally if that also signaled an octave down shift.

**Comment by daveyarwood** [comment]
I feel that this would only lead to confusion (and very funky-sounding scores) when sharing scores with others. The idea for `<` to be down and `>` to be up comes from MML. I can see where you are coming from, but I don't think it's worth introducing confusion about this from score to score.

On the plus side for your use case, a plugin system (#37) is being discussed -- once this is implemented, one could potentially write a plugin that swaps `<` and `>`, and there would be no confusion because it would be explicit in the score that this plugin is being used.
