### ISSUE TITLE
Browser-based Alda interpreter

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda#73]
cc: @kylestetz 

I think our ideal outcome is a "Try Alda" demo app, something akin to [tryclj.com](http://www.tryclj.com) and a thousand other existing "try X language" sites that let you try the language in an browser-based interpreter, without having to make the time investment of installing it on your computer.

Alda is a Clojure project, which means it must run in a JVM. While there are projects like Doppio that aim to provide a JVM within JavaScript, [Clojure support is probably spotty](https://github.com/plasma-umass/doppio/issues/106), and I'm skeptical that all the things we need our JVM to do (i.e. synthesize MIDI) are supported, especially across different browsers. 

So, I think the best way to do this would be to make an Alda server that listens on a WebSocket, receives strings of Alda code from a client, parses and executes them, then sends the resulting audio back over the WebSocket for the client to consume by playing it in the browser.

**Comment by kylestetz** [comment]
I see. While it's not going to have total interoperability or anything like that, I would strongly advocate for doing it all on the frontend and using the Web Audio API to handle the audio. It's going to give you much more real-time results, and it gives you the flexibility to bring in any kind of samples (or even allow the user to upload samples). In some sense it might provide opportunities you won't find in the pure clojure version!

I'm imagining that a lot of the parsing logic will port over to Javascript so that some custom timing work (to interpret the parsed data) would be all that needs to be rewritten. I could be way off about this though.

**Comment by daveyarwood** [comment]
Hmm... I'm starting to rethink this as I read more about the things JavaScript can do with audio. It looks like it's actually possible to play [MIDI music in the browser, even with soundfonts](http://blog.gleitzman.com/post/63283830260/midijs-playing-audio-in-the-browser-with)! Amazing stuff. 

What's your confidence level on being able to do everything Alda does (including playing MIDI with a nice-sounding soundfont) via JavaScript?

**Comment by kylestetz** [comment]
Confidence is high. I've done a lot of similar work in this area ([typedrummer](http://typedrummer.com) is like a mini alda!). Whether it gets parsed into MIDI and then run through something like midi.js, or whether we skip that step and write our own data-to-sound pipeline, sky's the limit.

**Comment by daveyarwood** [comment]
Awesome. I'm feeling good about this, then. I will table the idea I was proposing here -- we can always reopen it later if there is interest.

**Comment by daveyarwood** [comment]
P.S. I love typedrummer -- didn't know that was you!

**Comment by kylestetz** [comment]
:+1:
