### ISSUE TITLE
Editor Plugins

### ISSUE THREAD

**Issue by ArchimedesPi** [alda-lang/alda#83]
Plugins for editing Alda in various editors would be cool.
Currently written plugins:

- [x] [Sublime Text](https://github.com/archimedespi/sublime-alda)
- [x] [Atom](https://github.com/MadcapJake/language-alda)
- [x] [Vim](https://github.com/daveyarwood/vim-alda)
- [x] [Emacs](https://github.com/jgkamat/alda-mode)
- [ ] IntelliJ

I'm willing to do Sublime Text. If anyone wants to do a Vim plugin or Emacs major mode, great!
Also, I'm wondering if @daveyarwood would like the plugins under the alda-lang org? Maybe we could get @MadcapJake to move his repo into @alda-lang?

**Comment by kirbyfan64** [comment]
I'll make a bundle for [Howl](http://howl.io)!

**Comment by daveyarwood** [comment]
I'm very much in favor of this! I would especially love a Vim plugin.

I think the 4 editors listed here are a good starting point, being probably the main 4 editors that people use, and we should close this issue after that.

I don't think alda editor plugins need to be under the alda-lang org -- I would prefer to consider them "unofficial" and hosted elsewhere. If/when I make a Vim plugin\*, I will probably put it under daveyarwood instead of alda-lang.

\*I'm not volunteering to do this yet -- too many other things to take care of at the moment -- but if someone else feels like getting started, I'll gladly contribute!

**Comment by crisptrutski** [comment]
These editor modes should support talking to the REPL server once that's available, and the JS based editors should include some CLJS based playback when that lands too :sunglasses: 

Have been meaning to learn to emerge from my pupative state of emacs befuddlement and learn some elisp, so another *soft* offer covering the last of the "big 4" :smile:

**Comment by pkobrien** [comment]
I'll vote for Cursive support.

**Comment by crisptrutski** [comment]
[IntelliJ language tooling](https://github.com/JetBrains/Grammar-Kit) looks very approachable

**Comment by ArchimedesPi** [comment]
I've pretty much finished the sublime plugin, here's a screenshot:
![a syntax-highlighted Alda piece](http://i.imgur.com/BJk1Thd.png)

Do try it out! I'd love to get feedback on how usable the highlighting and other stuff is.

**Comment by daveyarwood** [comment]
@ArchimedesPi This looks awesome, bravo!

I have only two bits of feedback:

- I think accidentals should be the same color as notes, in order to better separate notes from durations (and unify the note letter with the accidental, into one conceptual pitch)

- It might be good to make voice events and markers a different color from instrument calls (e.g. `piano:`). Basically we want the instrument calls to pop out more, and be more distinct, IMHO.

**Comment by ArchimedesPi** [comment]
@daveyarwood: Thanks for the suggestions! The first is easy, the second is a bit harder.

**Comment by daveyarwood** [comment]
Do we have a limited number of colors available, so we would need to reuse an existing color?

**Comment by daveyarwood** [comment]
I've started working on a [Vim plugin](https://github.com/daveyarwood/vim-alda) as I read through [Learn Vimscript the Hard Way](http://learnvimscriptthehardway.stevelosh.com). I'll keep updating it as I add features, but right now it's pretty basic:

* filetype detection (*.alda)
* minimal syntax highlighting (need to add a lot of things)
* support for [vim-commentary](http://github.com/tpope/vim-commentary)

I think this will eventually become really cool -- I'm thinking there can be an operator (let's say `gp`) which will play snippets of Alda code. So, if you're editing a score, you can highlight a bunch of lines/columns in visual mode and type `gp` and it will send them to a running Alda server (will require #49) (starting one if there isn't already one running) and you'll hear the snippet of code being played immediately. Thanks to the awesome concept of Vim operators, you'll be able to easily play the line you're on with `gpp`, just the note your cursor is over with `gpiW`, the whole score with `ggVGgp`, etc. There could also be a way to open a prompt to send arbitrary text to the Alda server, which would be like an embedded Alda REPL inside of Vim!

**Comment by daveyarwood** [comment]
I'll consider this issue "done" when we have at least minimal support (i.e. file type recognition and basic syntax highlighting) for all 5 editors listed in the OP, and there is documentation pointing people towards these plug-ins. At that point, each plugin should continue to improve as more and more people start using it and contributing to its development.

We've got 3 down so far, only Emacs and IntelliJ are left!

**Comment by daveyarwood** [comment]
I've added links to the available editor plugins in the docs and README. We can add links to future editor plugins as they come.

**Comment by jgkamat** [comment]
I'm working on an emacs plugin right now (planning to get syntax highlighting done at a bare minimum). I'll post what I have once I get something basic working.

**Comment by daveyarwood** [comment]
@jgkamat That's awesome! I've been flirting with [Spacemacs](http://spacemacs.org/) lately -- I'll definitely check out alda-mode when I have a chance!

**Comment by jgkamat** [comment]
I've got a lot of progress done, I guess i'm 'finished' with the basic feature set described above. I'm going to keep working on it though (at a slower pace), and I'm working on getting it into melpa now. The most notable thing missing is support for block comments, I couldn't figure out how to do those. This is what I do have working:

- Syntax Highlighting (comments (including octave bars), instruments, voice, timing adjustments, cramming braces, accidentals, octave adjustments, variable adjustments '(vol 20)', markers)
- Indention (using asm-mode's indention policy, seems to fit alda code too)
- Enables automatically when installed on *.alda files
- Emacs comment (evil-commentary) plugins/functions should prepend `#` when commenting
- Playing alda song segments from within emacs (as described above)! =)

Alda song playback has some POSIX shell script bits, so its probably only going to work on linux/mac (maybe I'll fix that later). Playback is supported via both an emacs function (requires text selection), and evil integration. Both of these methods require a key mapping (see the repo README for details).

I've made a [video demoing the alda playback](https://www.youtube.com/watch?v=YsTGrBDqjuI), which shows both the standard emacs function (kbd `,a`) and the evil integration (kbd `gp`). The server takes a while to start on my machine (because my computer is pretty slow).

I messed with the colors on my system, so I'm not sure what the colors look like for other people. I'll change them if anyone wants. Let me know if you have any suggestions for improving it! You will need to load `alda-mode.el` manually as of now (until it gets in melpa).

**Comment by daveyarwood** [comment]
@jgkamat Wow, this looks great! Thanks for the video. Being able to play regions of the file is nice -- that's something I'm planning on adding to [vim-alda](https://github.com/daveyarwood/vim-alda) whenever I find a minute -- currently there is just a buffer-local mapping for playing the entire buffer; eventually I'll add a "play operator" with motions like you've done.

Very excited to tell my Emacs-using friends about this. Nice job! :smile: :+1:

**Comment by daveyarwood** [comment]
I'm going to go ahead and close this issue -- I think Sublime, Atom, Vim and Emacs is a strong foundation for Alda editor plugins -- very big thanks again to @ArchimedesPi @MadcapJake and @jgkamat for your contributions!!

If you're reading this and you've got the itch to add support for IntelliJ, Cursive, Howl, or anything else, please do! You can post a link here and/or submit a PR to update the Alda README with a link to your plugin.
