### ISSUE TITLE
Review Opusmodus for inspiration

### ISSUE THREAD

**Issue by pkobrien** [alda-lang/alda#91]
Especially their OMN language: http://opusmodus.com/omn.html

**Comment by daveyarwood** [comment]
Wow, this is really cool! I think the guy who created OM had almost the same motivation as me.

Random observations/thoughts:

- Now that Alda has inline Clojure code, I think it would be fairly easy to implement some of the syntax ideas from OMN. It might be a fun project to try to make a limited Alda "port" of OMN by defining functions and macros in the alda.lisp namespace.

- The creator of OMN also mentions in [this interview](http://www.musicradar.com/news/tech/composition-meets-programming-with-opusmodus-612252) that the user can extend the library with his own collection of ideas, patterns, etc. which is something I had in mind for Alda as well, via exposing access to the Clojure run-time with inline code.

- The "OMN" approach to composition is a bit different that Alda's. With OMN, you're writing Common Lisp, which requires some programming background. Alda is really more of a music markup language - WYSIWYG. I think both approaches are equally interesting and valuable. I am particularly interested in lowering the barrier to entry for people with little to no programming experience, while at the same time providing lower-level access to programmers who want to tinker. Finding that sweet spot is I think what will define Alda's personality as the language matures. Although the syntax of OMN is rather nice and fairly intuitive

- OM creates sound by automatically recognizing MIDI ports and sending MIDI signals. This would be a really fantastic feature for Alda to have -- it would allow people to use Alda syntax to control VSTs or even hardware synthesizers.

- OM does a lot of the things we want to do:
    - converting a MIDI file to its syntax
    - display the score as sheet music
    - export to MIDI or MusicXML
    - support for microtonal music

- OM costs about $600 US! It's a shame it's not FOSS, but hey, I guess programmers need to eat too. I'd love to see the source code. I wonder if it's written in Common Lisp, since OMN is written in Common Lisp. If so, it would be nice to compare and contrast the way the two languages are implemented.

**Comment by daveyarwood** [comment]
Closing this issue, but it's still here for posterity! :)

**Comment by opmoceo** [comment]
Could you change the link above to https://opusmodus.com
The .../omn.htlm is not working any more.
Thank you.
JP

**Comment by daveyarwood** [comment]
Edited.
